### ISSUE TITLE
C# CaseChangingCharStream implementation contains an error

### ISSUE THREAD

**Issue by Huwmungous** [antlr/grammars-v4#1829]
Lines 71 & 73 of CaseChangingCharStream.cs should read 'La' not 'LA'

**Comment by KvanTTT** [comment]
It's not error because there are different C# runtimes: [Standard](https://www.nuget.org/packages/Antlr4.Runtime.Standard/4.8) and [Optimized](https://www.nuget.org/packages/Antlr4.Runtime/). It looks like you are using the last one. Also, take a look at [this implementation of case changing stream](https://github.com/KvanTTT/DAGE/blob/master/AntlrGrammarEditor/AntlrRuntimes/CSharp/AntlrCaseInsensitiveInputStream.cs) where both of runtimes are supported by using preprocessor directives.
