### ISSUE TITLE
python-cs grammar generated code doesn't compile

### ISSUE THREAD

**Issue by nightblade9** [antlr/grammars-v4#1858]
Hi,

I'm trying to generate a bare-bones Python parser/lexer in C# code. Here's what I did so far:

- Set up Antlr4 according to the GitHub repo instructions
- Create a new .NET Core console app and add a package reference to `Antlr4.Runtime.Standard`
- Download `python/python3-cs/Python3.g4` to a subdirectory
- Run `java -jar ... -Dlanguage=CSharp Python3.g4 -o Generated`

This successfully spits out the usual files (base listener, lexer, parser). However, when I build/run my application, I get 4 errors; they are related to undefined instance variables named `_input` and `_tokenFactorySourcePair` in `Python3Lexer.cs`. Sure enough, those variables are not defined.

Am I doing something wrong, or does this just not work out-of-the-box? I found a couple of closed GitHub issues from 2015/2018 that mention that I might need to rip this out or change something, but I'm not sure how to do that.

**Comment by studentmain** [comment]
Use `python/python3`, it should works now.

**Comment by kaby76** [comment]
Please close https://github.com/antlr/grammars-v4/issues/1858. It no longer applies because the old [python/python3-cs grammar](https://github.com/antlr/grammars-v4/tree/13d869aef19d57013f75d530081ffc08de9bf466/python/python3-cs) was merged into the [python/python3 grammar](https://github.com/antlr/grammars-v4/tree/443916c7460a8f69e66666873c0088d2b3ec64c8/python/python3), has been cleaned up, and works for CSharp.
