### ISSUE TITLE
PHP grammar is missing

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#196]
It can be found here: https://github.com/teverett/phpGrammar

**Comment by cshapeshifter** [comment]
Note, that grammar does not support php >= 5.3 (namespaces, closures, etc.)

**Comment by teverett** [comment]
The grammar mentioned above was forward ported from this grammar for Antlr3

https://code.google.com/p/phpparser/

The original license is the 3-clause BSD license (http://opensource.org/licenses/BSD-3-Clause)

I have added some code to handle HTML entities and so on.

If it would be of interest to the Antlr community, I am happy to drop the code onto the grammarsv4 tree so that others could update it to support PHP languages features for PHP 5.3 and above.

**Comment by KvanTTT** [comment]
@teverett, it will be good to fill php gap in ANTLR.

**Comment by teverett** [comment]
Pull request #197

**Comment by KvanTTT** [comment]
I am working on new PHP ANTLR grammar of version 5.3 and later (based on [Phalanger](https://github.com/DEVSENSE/Phalanger) grammar). It will be uploaded soon.

**Comment by teverett** [comment]
Are we ok to close this issue then?

**Comment by KvanTTT** [comment]
I think yes. I'll upload my new PHP grammar when I test it on different projects and fix bugs as much as possible.
