### ISSUE TITLE
bcpl grammar - mutually left-recursive rules [vectorE] and [multE] and [repeatable_command, repeated_command]

### ISSUE THREAD

**Issue by matevosmehrabyan** [antlr/grammars-v4#2064]
ANTLR failed to generate lexer and parser for bcpl grammar, with the following error message:

`error(119): grammars-v4/bcpl/bcpl.g4::: The following sets of rules are mutually left-recursive [vectorE] and [multE] and [repeatable_command, repeated_command]`

ANTLR supports only direct left recursion.

**Comment by kaby76** [comment]
I will be working on this. I will be starting from the original reference, the Bcpl book, which I have had since 1983, and had worked on. I will provide a concise example of how to start from the "spec" grammar, and apply transformations via my grammar tool Trash to remove MLR.

**Comment by kaby76** [comment]
I have a PR for this. The three MLR were:

* vectorE. This rule contained a __useless grouping__ (i.e., parentheses) around an "alt", i.e., `vectorE : (vectorE '!' primaryE) | primaryE ;`. The grouping is unnecessary since the "|"-operator has lower priority than symbol concatenation.
* multE. This has the same problem as vectorE.
* repeatable_command/repeat_command. This MLR was in the original grammar. It's easily fixed with one unfold transform + one ungrouping.

--Ken

**Comment by kaby76** [comment]
@matevosmehrabyan In your convenience, please check the new BCPL grammar ([grammars-v4/bcpl/bcpl.g4](https://github.com/antlr/grammars-v4/blob/master/bcpl/bcpl.g4)) that we updated. It should be free of MLR now. The within the source are two other grammars for reference: the original grammar with the MLR in "[grammars-v4/bcpl/ignore/bcpl.g4](https://github.com/antlr/grammars-v4/blob/master/bcpl/ignore/bcpl.g4)" and the grammar from Richands' BCPL book, which I re-entered by hand, in "[grammars-v4/bcpl/origbcpl.g4](https://github.com/antlr/grammars-v4/blob/master/bcpl/origbcpl.g4)". Those two grammars both contain MLR, but are not used. Thanks! --Ken

**Comment by matevosmehrabyan** [comment]
I checked [grammars-v4/bcpl/bcpl.g4](https://github.com/antlr/grammars-v4/blob/master/bcpl/bcpl.g4), it doesn't contain MLR, Thanks!
