### ISSUE TITLE
C++ parameter types

### ISSUE THREAD

**Issue by gfour** [antlr/grammars-v4#2077]
I believe the C++ parser (CPP14Parser) does not correctly parse function parameters. Assume this piece of code (from [Boost](https://github.com/boostorg/interprocess/blob/develop/include/boost/interprocess/xsi_key.hpp)):
```
xsi_key(const char *path, boost::uint8_t id) {}
```
But, as shown in the screenshot, "id" is considered a "className" (while "path" is not).

![cpp-parseTree](https://user-images.githubusercontent.com/1374661/110969403-51a89080-8361-11eb-8f5b-f936599d647f.png)

**Comment by kstallard** [comment]
I also think there is something wrong with the CPP14Parser.g4.  

I've made some modifications that seem to fix it, but it still needs to be vetted with a wide variety of function parameters.

Disclaimer: I am not an Antlr expert...

[CPP14.zip](https://github.com/antlr/grammars-v4/files/6290649/CPP14.zip)

**Comment by kstallard** [comment]
Just made another commit that fixes the proper parsing of signdness and length modifiers.

**Comment by kstallard** [comment]
@gfour The general changes that are currently in a pull request now produce this using your example.

![antlr4_parse_tree_gfour_example](https://user-images.githubusercontent.com/5996043/114288580-80805800-9a2e-11eb-9cd0-1fa20246d090.png)

**Comment by kaby76** [comment]
The problem you found is caused by the ambiguity of the derivation of `parameter-decl`attribute-specifier-seqopt decl-specifier-seq declarator` vs. `attribute-specifier-seqopt decl-specifier-seq abstract-declaratoropt` in the [spec, page 1214](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf). In "const char* path”, the sequence “*path” must be derived from `declarator` because it involves a pointer. But, for "boost::uint8_t id", “id” is ill-considered as a class-name.

I have a different view on how this should be solved. The spec says how to disambiguate the parse: "If a type-name is encountered while parsing a decl-specifier-seq, it is interpreted as part of the decl-specifierseq if and only if there is no previous type-specifier other than a cv-qualifier in the decl-specifier-seq." _A type-name is part of the decl-specifier-seq only if preceded by only cv-qualifiers._ Consequently, “id” should be derived from `declarator` (=> `ptr-declarator` => `noptr-declarator` => `declarator-id attribute-specifier-seqopt ` => `id-expression` => `unqualified-id` => `identifier` => "id"). It is likely there are dozens of such rules in this and other related grammars (e.g., https://github.com/antlr/grammars-v4/issues/1979).

Although it is already off-spec, [the PR](https://github.com/antlr/grammars-v4/pull/2124) proposed takes the grammar further off-spec.

**Comment by kstallard** [comment]
@kaby76 Thank you for taking time to respond and review [this PR](https://github.com/antlr/grammars-v4/pull/2124).

So, essentially what you are saying is that we should remove the ambiguity and let higher level code determine if the declaration makes sense.  Yeah... I completely agree.  I just saw things in declspecifierseq that didn't make sense for parameters and thought narrowing the scope would be correct.  But I also knew that people smarter than me might see it differently.

But your approach is way more precise.  I'll fix it.  Thanks again for taking time to comment on this.

**Comment by kstallard** [comment]
@kaby76 I think I have a fix.  Take a look.  It does not follow the attribute-specifier-seqopt path however.   However, I am able remove the side show of a specific paramDeclSpecifierSeq.  Are you sure attribute-specifier-seqopt should be part of this?


Here is the result using @gfour 's example:
![antlr4_parse_tree_CPP14_correct_function_parsing_nongreedy](https://user-images.githubusercontent.com/5996043/114316546-4744f800-9ac1-11eb-9223-c0ab30a78ae4.png)

Here is his example with an attribute included in the parameter list
![antlr4_parse_tree_with_attribute](https://user-images.githubusercontent.com/5996043/114316928-f2a27c80-9ac2-11eb-88f0-0d18dc57624d.png)

Thoughts?

Thanks
Kevin

**Comment by kstallard** [comment]
@kaby76 I've been thinking about this some more, and I think your translation of the specification is correct.  Identifiers that cannot be preceded with a cvqualifier and are last in the list must be the variable name.

Even with this non-greedy fix...you are right, this grammar doesn't really match the specification.  Looking at the rules that make up declSpecifierSeq I don't see that it uses the criteria as you pointed out.

So while this latest fix prevents it from going further away from the specification, it still doesn't address the fundamental issue that you pointed out.

Would you agree that this recent fix (where the paramDeclSpecifierSeq is removed and the original declSpecifierSeq is made less greedy) is appropriate for the time being and maybe we can keep this as an outstanding defect to be corrected later?

I would like to see the grammar be more closely aligned with the C++ specification, but the pressures getting a product out are preventing me from going much deeper....

**Comment by kstallard** [comment]
This begs another question.  How can we write a grammar that will take into account the cvqualifier if the grammar doesn't have access to header files?

In other words...if we have a definition of uint8_t somewhere, how will the grammar know that a cvqualifier can be put in front of uint8_t?

Is it even possible to truly follow the specification using the grammar only?  Doesn't there have to be some higher level application code involved so that it can record and keep track of various type definitions?

**Comment by kaby76** [comment]
So, there are of course two ways to implement this: refactoring the grammar, which is what you did; or inserting semantic checks. I think it's worth thinking about this for a day or two before making a decision. There are pros and cons to any implementation.

@kstallard That looks like what should be produced.

I have a preliminary implementation [here](https://github.com/kaby76/alt-cpp) of what I was thinking about. However, I'd be very wary of it--I don't have a lot of confidence that it solves the problem and all cases. It's also only in C#, and I didn't implement it for Java. But, you may want to see what I did. Basically, if I see a typename, I go up the tree looking for context. If it's not part of a declSpecifierSeq, then it's ok (true) to consider this alt. Otherwise, if it's the last in the declSpecifierSeq, it's also fine. Otherwise, I check for a preceding cvQualifier.

--Ken

**Comment by kaby76** [comment]
Sorry for the delay, but I had to clean up some of my tool code to really look at the tree produced by my solution. (And, it's still not as nice as with the Antlr tool. Dotnet does not like WPF code so I have to rewrite MS's AGL library in Maui to even create a dotnet tool with Antlr parse tree graphs.)

I get exactly the same two trees as in your last message (for `xsi_key(const char *path, boost::uint8_t id) {}` and `xsi_key(const char * path , boost::uint8_t id [[ gnu ]]) {}`).

I think the way to proceed is to move forward with this PR. At some point, we should make a new grammar that starts over from the spec adding in semantic checks for these ambiguities. Then, really spend some time trying to understand the problem.

**Comment by kstallard** [comment]
Sounds great.  Thank you @kaby76

**Comment by gfour** [comment]
Hi all, sorry for the delay.
@kstallard Thanks for the PR! It looks good to me and indeed works for that Boost file that caused this issue. @kaby76 I also agree with your interpretation of the spec (although I am not an expert) and the whole approach.
