### ISSUE TITLE
Add support for mix cases

### ISSUE THREAD

**Issue by gmai2006** [antlr/grammars-v4#2183]
Need to support the mixed cases in query, schema, etc.  Enclosed is a proposed grammar that supports mixed cases and fixes
[MySqlLexer.txt](https://github.com/antlr/grammars-v4/files/6431755/MySqlLexer.txt)
[MySqlParser.txt](https://github.com/antlr/grammars-v4/files/6431756/MySqlParser.txt)

 a few minor issues

**Comment by studentmain** [comment]
https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Positive-Technologies#usage-important-note

**Comment by gmai2006** [comment]
Already read that but in practical applications, there may be a few edge cases.  Also, it is a simple change in the grammar to support mix cases without using a custom class as described in the following article.
https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md

**Comment by kaby76** [comment]
https://github.com/antlr/grammars-v4/issues?q=is%3Aissue+mixed+label%3Acase-insensitive

NB, I wrote a [transform in Trash](https://github.com/kaby76/Domemtech.Trash/blob/main/trull/CUlliteral.cs) (my static semantics compiler for Antlr grammars) to automatically change literals to the grammar-based approach and back. I did this because there were some grammars that have hundreds of hardwired uppercase or lowercase literals, and it takes a second to apply changes across the board without any errors and consistently. It isn't implemented as a stand-alone tool yet as I've been stuck on fixing other problems. But, I am planning to add this tool.

But, this raises the issue of what is the base grammar. You could have the grammar use fixed lowercase literals, and when you want case insensitive literals, apply transforms to get what you need. We are considering a transform to convert "this." syntax in actions for Go. Why is this--or any other transform--different? What constitutes the source?

**Comment by studentmain** [comment]
> What constitutes the source?

> The "source code" for a work means the preferred form of the work
for making modifications to it. -- GPL v3 chapter 1

So scraped grammar is not the source code, unless someone directly modified it.
Optimized grammar is the source code, we do optimize by hand.
Converted grammar is not the source code, unless we decide work on it directly.

Let's back to the specific problem: `A: [Aa];` or `CaseInsensitiveStream`. What's the difference, which is better, is it applied to other grammars?

**Comment by kaby76** [comment]
Well, I'm sure you read the code--it's pretty much a hack solution to solve case insensitive keywords. It does that by mapping a char to upper or lowercase (e.g., [here](https://github.com/antlr/grammars-v4/blob/master/_scripts/templates/CSharp/CaseChangingCharStream.cs#L74), [here](https://github.com/antlr/grammars-v4/blob/master/_scripts/templates/Cpp/CaseChangingCharStream.cpp#L55), [here](https://github.com/antlr/grammars-v4/blob/master/_scripts/templates/Cpp/CaseChangingCharStream.cpp#L55), etc). The problem with it is that it also rewrites string literals. If you then use the parse tree for code generation, your strings are all in one case.

The problem is that it's a bad solution that does not reflect a language specification. For this reason, a lot of people really don't like it. Most of the time a spec would say "keywords are case insensitive", not "all input is case insensitive". If the code was changed to rewrite only keyword tokens, then there might be a case of saying that this is a "good" way to implement this with Antlr. 

But, I'm not for this way of implementing a language. If you want to take the Antlr grammar and convert it to another format, another parser generator, you are screwed.

So, it's just my opinion, but I think it should be implemented `A: [aA];`.

But, should the grammar be `A: 'a';` or `A: [aA];` in the repo? I think the decision should be that if it's in the spec for the language, it should be explicit in the CFG. `A: 'a';` in itself does not reflect the spec for the language. If you were to implement it using semantic predicates, then you could add `{ isKeyword($text) }?` (or however Antlr would do that), then that might also be an okay implementation--it's in the CFG.

**Comment by kaby76** [comment]
Excellent information. Ty.

We have a few ways to deal with this.

1) Do nothing. There's already a workable solution via case folding streams, albeit not a great solution as I mentioned.
2) Rewrite the literals into sequential upper-/lowercase character sets, e.g., `A: 'abc';` => `A: [aA][bB][cC];` and check in as source. This has no perf hit, but a code size hit. Antlr would not be able to find reused equivalent sequence character sets, e.g., `A: [aA][bB][cC]; B:[aA][bB][cC]; C: 'abc';`. To handle issues like this, add additional checks to tranalyze and add in the tool into the build.
3) Rip out case folding streams from CI, leave the grammar as is, and add in trulliteral as a grammar code generation phase, which would rewrite the grammar by replacing rules with string literals with the u/l-case sequence character set form.
4) Replace the hardwired keyword rules with a `tokens {}` section that declares all keywords, then in the lexer rule for IDs perform a table lookup and rewrite the token type as a replacement.

The online document [here](https://dev.mysql.com/doc/refman/8.0/en/language-structure.html) for MySQL states:

    "SQL keywords are not case-sensitive and may be written in any lettercase. This manual uses uppercase."

So, if we do nothing, the grammar does not follow the language spec.

**Comment by KvanTTT** [comment]
> A: 'abc'; => A: [aA][bB][cC];

I would suggest

```g4
a: A B C;
fragment A: [Aa];
fragment B: [Bb];
fragment C: [Cc];
```

**Comment by KvanTTT** [comment]
MySql grammar now uses [caseInsensitive](https://github.com/antlr/antlr4/blob/master/doc/options.md#caseinsensitive) option.
