### ISSUE TITLE
url grammar error on strings with numbers

### ISSUE THREAD

**Issue by idawson-gl** [antlr/grammars-v4#2197]
Similar to https://github.com/antlr/grammars-v4/issues/875

URLs that have single digits cause a mismatched input error:
examples:

https://github.com/1/
https://github.com/1
https://github.com/asdf/2?
https://github.com/a?1=2

I'm assuming this is due to `([a-zA-Z~0-9] | HEX) ([a-zA-Z0-9.+-] | HEX)*` but i am pretty new to antlr v4 grammar!

**Comment by bkiers** [comment]
It also fails to parse multiple digits: `https://github.com/12345`. It is because of how ANTLR's lexer matches characters: it  tries to match as much characters as possible, and when 2 or more  rules match the same amount of characters, the rule defined  first "wins".

So  `12345` (or `1`) matches both `DIGITS` and `STRING`, but since `DIGITS` is defined first, it "wins". And input like `12345a` matches `STRING` (try to match as much as possible).
