### ISSUE TITLE
The license of JSON.g4

### ISSUE THREAD

**Issue by Changochen** [antlr/grammars-v4#2277]
Hi. I want to use the JSON.g4 in my project but I am not sure about its license.

As https://github.com/antlr/grammars-v4/wiki states, :
"There is no single license for the grammars, each grammar has its own license. Check inside the grammar files for licensing terms."

However, the [JSON.g4](https://github.com/antlr/grammars-v4/blob/master/json/JSON.g4) has no license. It said it's taken from "The Definitive ANTLR 4 Reference" by Terence Parr. Since the antlr project itself is under BSD license, is this file also under BSD license?

**Comment by KvanTTT** [comment]
See https://github.com/antlr/grammars-v4/issues/2277 It seems like the license file is still missing in repository. Please add [BSD license with the advertising clause](https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_%22BSD_License%22)) to the repository if you can. Also, I don't think it's a big deal because JSON grammar is open, small and widespread.

**Comment by Changochen** [comment]
Thanks! I just want to make sure that I follow the license rules.

Just a minor correction, the referenced issue should be https://github.com/antlr/grammars-v4/issues/1607.
