### ISSUE TITLE
VB6 visitor issue

### ISSUE THREAD

**Issue by lsalamon** [antlr/grammars-v4#2290]
This simple VB code generates wrong visitor events for `Dim` statement:

```vb
Public Function VarLongDim() As Long
Dim number As Long
number = 1234
VarLongDim = number
End Function
```

`ExitBlock` and `ExitEveryRule` occur long after the block is evaluated.

What could be the cause of this behavior?

**Comment by kaby76** [comment]
I wrote a _listener_ class (C#) that outputs when the `EnterBlock`, `ExitBlock`, `EnterVariableStmt`, `ExitVariableStmt`, and `ExitEveryRule` methods are called. The code ran exactly as expected (see the output below). There is only one `block` parse tree node, and only one `variableStmt` parse tree node (which is a descendant of the `block` node).

Parse tree:


	( startRule
	  ( module
	    ( moduleBody
	      ( moduleBodyElement
		( functionStmt
		  ( visibility
		    ( PUBLIC i=0 txt=Public tt=129 DEFAULT_TOKEN_CHANNEL
		  ) ) 
		  ( WS i=6 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
		  ) 
		  ( FUNCTION i=7 txt=Function tt=70 DEFAULT_TOKEN_CHANNEL
		  ) 
		  ( WS i=15 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
		  ) 
		  ( ambiguousIdentifier
		    ( IDENTIFIER i=16 txt=VarLongDim tt=218 DEFAULT_TOKEN_CHANNEL
		  ) ) 
		  ( argList
		    ( LPAREN i=26 txt=( tt=194 DEFAULT_TOKEN_CHANNEL
		    ) 
		    ( RPAREN i=27 txt=) tt=205 DEFAULT_TOKEN_CHANNEL
		  ) ) 
		  ( WS i=28 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
		  ) 
		  ( asTypeClause
		    ( AS i=29 txt=As tt=8 DEFAULT_TOKEN_CHANNEL
		    ) 
		    ( WS i=31 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
		    ) 
		    ( type_
		      ( baseType
			( LONG i=32 txt=Long tt=85 DEFAULT_TOKEN_CHANNEL
		  ) ) ) ) 
		  ( NEWLINE i=36 txt=\r\n tt=220 DEFAULT_TOKEN_CHANNEL
		  ) 
		  ( block
		    ( blockStmt
		      ( variableStmt
			( DIM i=38 txt=Dim tt=40 DEFAULT_TOKEN_CHANNEL
			) 
			( WS i=41 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
			) 
			( variableListStmt
			  ( variableSubStmt
			    ( ambiguousIdentifier
			      ( IDENTIFIER i=42 txt=number tt=218 DEFAULT_TOKEN_CHANNEL
			    ) ) 
			    ( WS i=48 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
			    ) 
			    ( asTypeClause
			      ( AS i=49 txt=As tt=8 DEFAULT_TOKEN_CHANNEL
			      ) 
			      ( WS i=51 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
			      ) 
			      ( type_
				( baseType
				  ( LONG i=52 txt=Long tt=85 DEFAULT_TOKEN_CHANNEL
		    ) ) ) ) ) ) ) ) 
		    ( NEWLINE i=56 txt=\r\n tt=220 DEFAULT_TOKEN_CHANNEL
		    ) 
		    ( blockStmt
		      ( letStmt
			( implicitCallStmt_InStmt
			  ( iCS_S_VariableOrProcedureCall
			    ( ambiguousIdentifier
			      ( IDENTIFIER i=58 txt=number tt=218 DEFAULT_TOKEN_CHANNEL
			) ) ) ) 
			( WS i=64 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
			) 
			( EQ i=65 txt== tt=187 DEFAULT_TOKEN_CHANNEL
			) 
			( WS i=66 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
			) 
			( valueStmt
			  ( literal
			    ( INTEGERLITERAL i=67 txt=1234 tt=212 DEFAULT_TOKEN_CHANNEL
		    ) ) ) ) ) 
		    ( NEWLINE i=71 txt=\r\n tt=220 DEFAULT_TOKEN_CHANNEL
		    ) 
		    ( blockStmt
		      ( letStmt
			( implicitCallStmt_InStmt
			  ( iCS_S_VariableOrProcedureCall
			    ( ambiguousIdentifier
			      ( IDENTIFIER i=73 txt=VarLongDim tt=218 DEFAULT_TOKEN_CHANNEL
			) ) ) ) 
			( WS i=83 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
			) 
			( EQ i=84 txt== tt=187 DEFAULT_TOKEN_CHANNEL
			) 
			( WS i=85 txt=  tt=222 DEFAULT_TOKEN_CHANNEL
			) 
			( valueStmt
			  ( implicitCallStmt_InStmt
			    ( iCS_S_VariableOrProcedureCall
			      ( ambiguousIdentifier
				( IDENTIFIER i=86 txt=number tt=218 DEFAULT_TOKEN_CHANNEL
		  ) ) ) ) ) ) ) ) 
		  ( NEWLINE i=92 txt=\r\n tt=220 DEFAULT_TOKEN_CHANNEL
		  ) 
		  ( END_FUNCTION i=94 txt=End Function tt=47 DEFAULT_TOKEN_CHANNEL
	    ) ) ) ) 
	    ( NEWLINE i=106 txt=\r\n tt=220 DEFAULT_TOKEN_CHANNEL
	  ) ) 
	  ( EOF i=108 txt= tt=-1 DEFAULT_TOKEN_CHANNEL
	) ) 


Code:

	public class Foo : VisualBasic6ParserBaseListener
	{
	    public override void EnterBlock([NotNull] VisualBasic6Parser.BlockContext context)
	    {
		System.Console.WriteLine("EnterBlock");
	    }
	    public override void ExitBlock([NotNull] VisualBasic6Parser.BlockContext context)
	    {
		System.Console.WriteLine("ExitBlock");
	    }
	    public override void EnterVariableStmt([NotNull] VisualBasic6Parser.VariableStmtContext context)
	    {
		System.Console.WriteLine("EnterVariableStmt");
	    }
	    public override void ExitVariableStmt([NotNull] VisualBasic6Parser.VariableStmtContext context)
	    {
		System.Console.WriteLine("ExitVariableStmt");
	    }
	    public override void ExitEveryRule([NotNull] ParserRuleContext context)
	    {
		System.Console.WriteLine("ExitEveryRule");
	    }
	}

Output:

	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	EnterBlock
	EnterVariableStmt
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitVariableStmt
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitBlock
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule
	ExitEveryRule

**Comment by lsalamon** [comment]
I did a poc to reproduce the case in csharp.
Project link:
https://tmpfiles.org/97428/vb6parsetest.zip

                                                            ExitEveryRule*(4)VarLongDim
                                                        ExitBlockStmt*(4)VarLongDim
                                                    ExitEveryRule*(4)VarLongDim
                                                ExitBlock*(2)Dim
                                            ExitEveryRule*(2)Dim
                                            VisitTerminal*--->End Function
                                        ExitFunctionStmt*(1)Public
                                    ExitEveryRule*(1)Public
                                ExitModuleBodyElement*(1)Public
                            ExitEveryRule*(1)Public
                        ExitModuleBody*(1)Public
                    ExitEveryRule*(1)Public
                ExitModule*(1)Public
            ExitEveryRule*(1)Public
            VisitTerminal*---><EOF>
        ExitStartRule*(1)Public
    ExitEveryRule*(1)Public

**Comment by kaby76** [comment]
I am using the official Antlr4 tool and runtime ([source](https://github.com/antlr/antlr4) [runtime](https://www.nuget.org/packages/Antlr4.Runtime.Standard/) [tool](https://www.antlr.org/download/antlr-4.9.2-complete.jar)). The code you are using Harwell's fork ([source](https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.6.6) [tool](https://www.nuget.org/packages/Antlr4/) [runtime](https://www.nuget.org/packages/Antlr4.Runtime/)). Note, Harwell's code hasn't been updated in several years, and when forked from https://github.com/antlr/antlr4 was already a year or two behind. The current version for official Antlr4 is 4.9.2.

But, the official version of Antlr4 and Harwell's version do not generate the same set of listener methods! For Official Antlr4, the tool does not generate methods for "labeled alts": `EnterModuleOption`, `ExitModuleOption`, `EnterIfThenElseStmt`, `ExitIfThenElseStmt`, `EnterSC_Cond`, `ExitSC_Cond`, `EnterSC_CondExpr`, `ExitSC_CondExpr`, `EnterValueStmt`, `ExitValueStmt`. Labeled alts are those alts in the grammar that are marked with '#' and label. I found this out when I tried to port your code to Official Antlr4, and then got compiler errors indicating I'm trying to override methods that don't exist in the listener base class.

I don't know why there is a difference in listeners between Official Antlr4 and Harwell's fork. But, it does seem that there might be some ambiguity in which listener method is called for both the rule and its labeled alt in Harwell's code.

In any case, Official Antlr4 looks fine. Could you please explain what you expect, where the error is, what listener method is called out of order?

**Comment by lsalamon** [comment]
Thanks for the clarification. I will update the project using the latest version. Thanks.

**Comment by lsalamon** [comment]
Just for the record. I set up a project using both versions both using the same Antlr4 grammar and both produce the same results.

**Comment by kaby76** [comment]
Goodness. If you are still claiming that the listener methods are performed out of order, then let's try to identify this problem rather than brush it under the rug, and just close off the issue. This isn't how progress is made.

The only really good way to discuss this and to prove that there is a problem is to use DFS numberings (see [Wiki](https://en.wikipedia.org/wiki/Depth-first_search#Example)).

Attached is a zip file 
[xxx.zip](https://github.com/antlr/grammars-v4/files/7034333/xxx.zip)
 with two C#-target programs, one in Antlr4cs and the other in Official Antlr4, that computes the DFS number of the parse tree node. The Antlr tree walker is different from a normal tree walker because it does not visit leaf nodes, because there are no `Enter` or `Exit` methods for lexer rules. But, I've included the numbering both ways, one where all nodes in the parse tree are numbered with a DFS order, and the other where the leaves are left out. In the output, the number of the node, e.g., `2` as in the tree node `moduleBody 2` is the DFS number. For an `Enter` or `Exit` call, the node is identified with the DFS number. This way we can synch up the node with the actual call. In addition, with DFS numbering in hand, we can insert assertions to check the validity of the tree traversal.

The main program first parses, then computes the DFS numbering, then runs the tree walker. The DFS number is a straight forward recursive implementation:

        static Dictionary<IParseTree, int> dfs = new Dictionary<IParseTree, int>();
        static int order = 0;
        static Dictionary<IParseTree, int> weird_dfs = new Dictionary<IParseTree, int>();
        static int weird_order = 0;

        static void ComputeDFS(IParseTree tree)
        {
            dfs[tree] = order++;
            if (!(tree is TerminalNodeImpl))
            {
                weird_dfs[tree] = weird_order++;
            }
            for (int i = 0; i < tree.ChildCount; ++i)
            {
                var c = tree.GetChild(i);
                ComputeDFS(c);
            }
        }

With DFS numbering, we can now write assertions within the Listener that identify out-of-order conditions.
 
* On a call to an `Enter` method for a parser rule (e.g., `EnterAmbiguousIdentifier(context)` not `EnterEveryRule`),
    * Compute a DFS number via the Antlr tree walker, compares that to what I computed in the method `Convert`.
    * Verify that there is no call to `EnterEveryRule` for node `context` after this method is called.
    * Verify that there all previous calls to `Enter` for a rule is called only for nodes that have a lower DFS number.
* On a call to an `Exit` method for a parser rule (e.g., `ExitAmbiguousIdentifier(context)`),
    * Verify that the corresponding `Enter` call was made (e.g., ` EnterAmbiguousIdentifier`).
    * Verify for all descendants `p` of `context`, the `Enter` and `Exit` methods were called prior to this `Exit` method for `context`.
* For the `EnterEveryRule`, we verify that it was not called before, and note that it was called for the node with the given DFS number.
* For the `ExitEveryRule`, we verify that it was not called before, and note that it was called fro the node with the given DFS number.

For the input, there were no assertions triggered. The output from the program was identical between the two C# programs.

	bash test.sh
	../examples/in.txt
	EnterEveryRule 0
	EnterStartRule 0
	EnterEveryRule 1
	EnterModule 1
	EnterEveryRule 2
	EnterModuleBody 2
	EnterEveryRule 3
	EnterModuleBodyElement 3
	EnterEveryRule 4
	EnterFunctionStmt 4
	EnterEveryRule 5
	EnterVisibility 5
	ExitVisibility 5
	ExitEveryRule 5
	EnterEveryRule 10
	EnterAmbiguousIdentifier 10
	ExitAmbiguousIdentifier 10
	ExitEveryRule 10
	EnterEveryRule 12
	EnterArgList 12
	ExitArgList 12
	ExitEveryRule 12
	EnterEveryRule 16
	EnterAsTypeClause 16
	EnterEveryRule 19
	EnterType_ 19
	EnterEveryRule 20
	EnterBaseType 20
	ExitBaseType 20
	ExitEveryRule 20
	ExitType_ 19
	ExitEveryRule 19
	ExitAsTypeClause 16
	ExitEveryRule 16
	EnterEveryRule 23
	EnterBlock 23
	EnterEveryRule 24
	EnterBlockStmt 24
	EnterEveryRule 25
	EnterVariableStmt 25
	EnterEveryRule 28
	EnterVariableListStmt 28
	EnterEveryRule 29
	EnterVariableSubStmt 29
	EnterEveryRule 30
	EnterAmbiguousIdentifier 30
	ExitAmbiguousIdentifier 30
	ExitEveryRule 30
	EnterEveryRule 33
	EnterAsTypeClause 33
	EnterEveryRule 36
	EnterType_ 36
	EnterEveryRule 37
	EnterBaseType 37
	ExitBaseType 37
	ExitEveryRule 37
	ExitType_ 36
	ExitEveryRule 36
	ExitAsTypeClause 33
	ExitEveryRule 33
	ExitVariableSubStmt 29
	ExitEveryRule 29
	ExitVariableListStmt 28
	ExitEveryRule 28
	ExitVariableStmt 25
	ExitEveryRule 25
	ExitBlockStmt 24
	ExitEveryRule 24
	EnterEveryRule 40
	EnterBlockStmt 40
	EnterEveryRule 41
	EnterLetStmt 41
	EnterEveryRule 42
	EnterImplicitCallStmt_InStmt 42
	EnterEveryRule 43
	EnterICS_S_VariableOrProcedureCall 43
	EnterEveryRule 44
	EnterAmbiguousIdentifier 44
	ExitAmbiguousIdentifier 44
	ExitEveryRule 44
	ExitICS_S_VariableOrProcedureCall 43
	ExitEveryRule 43
	ExitImplicitCallStmt_InStmt 42
	ExitEveryRule 42
	EnterEveryRule 49
	EnterVsLiteral 49
	EnterEveryRule 50
	EnterLiteral 50
	ExitLiteral 50
	ExitEveryRule 50
	ExitVsLiteral 49
	ExitEveryRule 49
	ExitLetStmt 41
	ExitEveryRule 41
	ExitBlockStmt 40
	ExitEveryRule 40
	EnterEveryRule 53
	EnterBlockStmt 53
	EnterEveryRule 54
	EnterLetStmt 54
	EnterEveryRule 55
	EnterImplicitCallStmt_InStmt 55
	EnterEveryRule 56
	EnterICS_S_VariableOrProcedureCall 56
	EnterEveryRule 57
	EnterAmbiguousIdentifier 57
	ExitAmbiguousIdentifier 57
	ExitEveryRule 57
	ExitICS_S_VariableOrProcedureCall 56
	ExitEveryRule 56
	ExitImplicitCallStmt_InStmt 55
	ExitEveryRule 55
	EnterEveryRule 62
	EnterVsICS 62
	EnterEveryRule 63
	EnterImplicitCallStmt_InStmt 63
	EnterEveryRule 64
	EnterICS_S_VariableOrProcedureCall 64
	EnterEveryRule 65
	EnterAmbiguousIdentifier 65
	ExitAmbiguousIdentifier 65
	ExitEveryRule 65
	ExitICS_S_VariableOrProcedureCall 64
	ExitEveryRule 64
	ExitImplicitCallStmt_InStmt 63
	ExitEveryRule 63
	ExitVsICS 62
	ExitEveryRule 62
	ExitLetStmt 54
	ExitEveryRule 54
	ExitBlockStmt 53
	ExitEveryRule 53
	ExitBlock 23
	ExitEveryRule 23
	ExitFunctionStmt 4
	ExitEveryRule 4
	ExitModuleBodyElement 3
	ExitEveryRule 3
	ExitModuleBody 2
	ExitEveryRule 2
	ExitModule 1
	ExitEveryRule 1
	ExitStartRule 0
	ExitEveryRule 0
	startRule 0
	   module 1
	      moduleBody 2
		 moduleBodyElement 3
		    functionStmt 4
		       visibility 5
			  PUBLIC 6 (Public)
		       WS 7 ( )
		       FUNCTION 8 (Function)
		       WS 9 ( )
		       ambiguousIdentifier 10
			  IDENTIFIER 11 (VarLongDim)
		       argList 12
			  LPAREN 13 (()
			  RPAREN 14 ())
		       WS 15 ( )
		       asTypeClause 16
			  AS 17 (As)
			  WS 18 ( )
			  type_ 19
			     baseType 20
				LONG 21 (Long)
		       NEWLINE 22 (
	)
		       block 23
			  blockStmt 24
			     variableStmt 25
				DIM 26 (Dim)
				WS 27 ( )
				variableListStmt 28
				   variableSubStmt 29
				      ambiguousIdentifier 30
					 IDENTIFIER 31 (number)
				      WS 32 ( )
				      asTypeClause 33
					 AS 34 (As)
					 WS 35 ( )
					 type_ 36
					    baseType 37
					       LONG 38 (Long)
			  NEWLINE 39 (
	)
			  blockStmt 40
			     letStmt 41
				implicitCallStmt_InStmt 42
				   iCS_S_VariableOrProcedureCall 43
				      ambiguousIdentifier 44
					 IDENTIFIER 45 (number)
				WS 46 ( )
				EQ 47 (=)
				WS 48 ( )
				valueStmt 49
				   literal 50
				      INTEGERLITERAL 51 (1234)
			  NEWLINE 52 (
	)
			  blockStmt 53
			     letStmt 54
				implicitCallStmt_InStmt 55
				   iCS_S_VariableOrProcedureCall 56
				      ambiguousIdentifier 57
					 IDENTIFIER 58 (VarLongDim)
				WS 59 ( )
				EQ 60 (=)
				WS 61 ( )
				valueStmt 62
				   implicitCallStmt_InStmt 63
				      iCS_S_VariableOrProcedureCall 64
					 ambiguousIdentifier 65
					    IDENTIFIER 66 (number)
		       NEWLINE 67 (
	)
		       END_FUNCTION 68 (End Function)
	      NEWLINE 69 (
	)
	   EOF 70 (<EOF>)

With the output in hand, I carefully compared each and every `Enter` and `Exit` method call with each node in the parse tree. It appears exactly as what I would expect.
* `EnterEveryRule` is called before an `Enter` parser rule method for a particular node. E.g., we see `EnterEveryRule 57` called before the corresponding enter method `EnterAmbiguousIdentifier 57`, not the other way around.
* `ExitEveryRule` is called after an `Exit` parser rule node method for a particular node. E.g., we see `ExitEveryRule 55` after `ExitImplicitCallStmt_InStmt 55`, not the other way around.
* No `Enter` or `Exit` are missing, and each is paired with the other. I actually did the pairing manually, but one could also do a quick check with grep (`cat out | grep -v EnterEveryRule | grep $'[\s\t]Enter' | wc; cat out | grep -v ExitEveryRule | grep $'[\s\t]Exit' | wc` and compare the word counts.
* `EnterEveryRule` and `ExitEveryRule` are never called for any leaf nodes (TerminalNodeImpl) of the parse tree.
* For parse tree node `valueStmt 49`, the "Enter" method called is `EnterVsLiteral`, not `EnterValueStmt`. In Antlr4cs, you can actually override the method (see Listener2.cs in the source code), since it's in the listener base class. In Antlr Standard/Original, you *cannot* override the method, so there's no chance of confusion. In my opinion, Antlr4cs is misleading because you may think that it could be called, but it will never be called.
* The order of the method calls follows the DFS ordering. In fact, it's a standard "LR-attribute evaluation" which is exactly what I would expect.
