### ISSUE TITLE
"The name '_input' does not exist in the current context"

### ISSUE THREAD

**Issue by tianhuat** [antlr/grammars-v4#231]
I got the error when using ECMAScript.CSharpTarget.g4, with C# target (antlr-csharp-runtime-4.5.1.zip) download here:
http://www.antlr.org/download.html

"The name '_input' does not exist in the current context"

**Comment by parrt** [comment]
likely it has embedded java code or something.

**Comment by jpwiddy** [comment]
I get this same exact error. 

I was using the ECMAScript.g4

**Comment by ajdnaranjo** [comment]
I got the same error when I've "CSharpSharwell" grammar  is generated. I'm using antlr-4.7-complete.jar to generate C# classes and nuget package Antlr4.Runtime.Standard.4.7.1

![img](https://user-images.githubusercontent.com/17502787/32806352-39298ed4-c95a-11e7-8e92-4c1b8c557d42.PNG)

Can anyone helpme whit this issue

**Comment by viversba** [comment]
Were you able to solve it @ajdnaranjo ?
I'm having the exact same problem

**Comment by Marti2203** [comment]
Hello, I think I may have resolved this issue.

**Comment by eeskildsen** [comment]
I get the same error in [`PlSqlLexerBase`](https://github.com/antlr/grammars-v4/blob/805b32407c92cc496f55bfdcfd9ef8c897757214/sql/plsql/CSharp/PlSqlLexerBase.cs#L14).

The problem seems to be that [`_input` is `private` in the C# `Lexer` base class](https://github.com/antlr/antlr4/blob/4779b8f6e45fb88261efb984cf9dbd2243e0cb2b/runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Lexer.cs#L35). Looks like it needs to be `protected`.

**Comment by Marti2203** [comment]
I can work on it if needed @eeskildsen .
