### ISSUE TITLE
[PostgreSQL] - Need a language agnostic PostgreSQL grammar

### ISSUE THREAD

**Issue by gmai2006** [antlr/grammars-v4#2373]
Issue:
Need a language-agnostic PostgreSQL grammar so it can be used to generate different target languages

Proposal
Took the liberty to download the current grammar (specific to C#) remove all actions from the parser and lexer grammars, modify it, and test against all samples include some from the failed folders.  All tests are passed

Note:  The current lexer grammar has actions in the Operator rule and I think due to the bug in the grammar itself which cannot distinguish the comment from the operator.  Remove the actions and replace the Operator rule with specific operators from the PostgreSQL official website fixes the issue

One exception:
One action cannot be removed from the lexer is the DollarStringConstant due to the fact that it is needed to check the token value.  

Question:
Do we want to add another PostgreSQL grammar that can be used to generate different target languages?

Enclosed is the proposed grammar for reference and review
[PostgreSQLLexer.txt](https://github.com/antlr/grammars-v4/files/7436590/PostgreSQLLexer.txt)
[PostgreSQLParser.txt](https://github.com/antlr/grammars-v4/files/7436591/PostgreSQLParser.txt)

**Comment by gmai2006** [comment]
Found other issues while parsing the PostgreSQL
- Recursive rules => create lots of unnecessary nested branches in the parse tree
- Epsilon rules => create lots of empty nodes in the parse tree

Took the liberty to refactor the grammar
- Replace recursive rules with iterative (list: | list item => list: item (item)*
- Replace the epsilon rules with an optional (?)
- Clean up all temporary rules - A rule that is declared as a label to another rule

The latest version is still in my repo.  It passed all tests.
https://github.com/gmai2006/grammar/tree/main/src/main/java/com/datascience9/postgres/parse

**Comment by kaby76** [comment]
The use of a grammar per target is not the best way to achieve a target-agnostic grammar. You should move the `@member` code to a base class, and action code encapsulated in a method. Please see java/java9, rust, python/python3. It is likely that a target independent grammar will have to be preprocessed into an Antlr grammar at some point as modifications for a target independent actions will never be added to Antlr. There has been a lot of discussion about this over years, but no decisions have been made. It is very likely a preprocessor will be implemented, as we just talked about adding one, in StackOverflow, to implement the tree construction operators that were removed in Antlr version 4.

**Comment by gmai2006** [comment]
Thanks.  It is an excellent idea.  Will create a base class.

**Comment by kaby76** [comment]
@gmai2006 Thanks. That will work well. We are definitely thinking about a target-independent action source code language, but it will take a while to figure out what best to include because we still have only a dozen or so examples in this repo. Every new example helps.

**Comment by gmai2006** [comment]
@kaby76 
A base class has been added to make the grammar a bit more agnostics.  

Question:  Do we want to add this grammar as another Postgres grammar? Let me how we want it.  I will create a branch and make a PR.

The changes are in still in my repo
https://github.com/gmai2006/grammar/blob/main/src/main/java/com/datascience9/postgres/parse/PostgreSQLLexer.g4

Thanks

**Comment by kaby76** [comment]
@gmai2006 I'm just looking over the C#-target code. Unfortunately, I don't see much commenting. Did you figure out why there is [a call to ParseRoutineBody()](https://github.com/antlr/grammars-v4/blob/master/sql/postgresql/PostgreSQLParser.g4#L40) in the action for rule `createfunc_opt_item`? The action involves navigating around a bit, yanking out the text for the sub-tree, [creating a new lexer and parser](https://github.com/antlr/grammars-v4/blob/master/sql/postgresql/PostgreSQLParser.g4#L36), parsing that conditionally  [one way]() or [another](https://github.com/antlr/grammars-v4/blob/master/sql/postgresql/PostgreSQLParser.g4#L43). The effort seems important because I do something very similar for the complete rewrite of the C++14 grammar (and new implementations for C++17, 20, and 23 that I'm also writing) where I support a full C++ preprocessor with cached headers for GNU, Clang, and MS C++. I haven't read the code to see if the lexer mode or grammar altogether is switched from the usual lexer.

**Comment by gmai2006** [comment]
Reviewed the action and if I may propose is to move the action to a later stage using the divide and conquer approach
1. Construct a parse tree according to the language specification (e.g. leave as it is: AS 'definition')
2. If need to extract or transform those functions we can use Visitor or even better Xpath.  We should be able to detect the type of function either SQL or PLSQL and we can send that branch to another parser to parse it

Since we just want to check the type of the function the XPath should do the trick after having the parse tree constructed
example: XPath = '//createfunctionstmt/createfunc_opt_list/createfunc_opt_item/func_as'

Let me know what you think.

**Comment by OleksiiKovalov** [comment]
> Did you figure out why there is [a call to ParseRoutineBody()](https://github.com/antlr/grammars-v4/blob/master/sql/postgresql/PostgreSQLParser.g4#L40) in the action for rule `createfunc_opt_item`?
procedure/function body in PostgreSQL is defined as string (usually - DollarQuoted) so to have proc/func body to be included in parsed tree we need to do additional parsing of such string

**Comment by gmai2006** [comment]
@OleksiiKovalov Recommend to defter that step.  Once the parse tree is constructed one can use Xpath to determine the function type and use the Visitor to parse the function branch if needed.

**Comment by OleksiiKovalov** [comment]
also there is a different approach from PostgreSQL which can in pg/plsql do "read text till semicolon/THEN/<keyword>" etc - in ANTLR grammar it is replaced by

**Comment by kaby76** [comment]
Is there an example that contains these special literals that are/were parsed using [ParseRoutineBody](https://github.com/antlr/grammars-v4/blob/92a5c8b97d20df965d7e187d6ecfb5f06de10b57/sql/postgresql/PostgreSQLParser.g4#L21). What does the Manual (Spec?) say about these literals?

**Comment by OleksiiKovalov** [comment]
https://www.postgresql.org/docs/12/plpgsql-structure.html
CREATE FUNCTION somefunc(integer, text) RETURNS integer
AS **'function body text'**
LANGUAGE plpgsql;

samples can be found at https://github.com/antlr/grammars-v4/blob/92a5c8b97d20df965d7e187d6ecfb5f06de10b57/sql/postgresql/examples/plpgsql-control-structures.sql
https://github.com/antlr/grammars-v4/blob/92a5c8b97d20df965d7e187d6ecfb5f06de10b57/sql/postgresql/examples/plpgsql.sql

**Comment by kaby76** [comment]
_Note, this is just a summary of the "spec-like" sections that pertain to Dollar-quoted string constants and the Sql Procedural Language for people who are experts in parsing--like me--but are not experts in SQL._

_There's a large chapter in the PostgreSql manual devoted to Pl/PgSql: [Chapter 43. PL/pgSQL — SQL Procedural Language](https://www.postgresql.org/docs/14/plpgsql.html). Dollar-Quoted String Constants is [Section 4.1.2.4](https://www.postgresql.org/docs/14/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS). It's important to note that if a dollar-quoted string literal is followed by `language`, then it should be treated special._

_Currently, the lexer switches modes to lex a dollar-quoted string literal as a sequence of `DollarText` tokens. At the end of the dollar-quoted string literal, the code pops the lexer mode to continue with the normal tokenization. When parsing a `createfunc_opt_list`, a whole new parser and lexer are created with the input formed by serializing the `DollarText` tokens, and the parse tree modified (`public IParseTree Definition;`)._

**But, if the lexer grammar contains both the SQL tokens and PL tokens in the same (default) lexer mode. It is unnecessary to create a new parser to parse the re-serialized DollarText tokens because the lexer can treat the string literal special.**

You only have to handle two cases:

* In the lexer, scan as far ahead as needed to find the end of the dollar-quoted string literal. Continue to scan past that and look for `language plpgsql` or `language sql`. Tokenize the dollar-quoted string as `BeginDollarStringConstant`, whatever normally tokenized in default mode, then `EndDollarStringConstant`. The parser rule `anysconst` can then be modified as:

    BeginDollarStringConstant (stmtblock | pl_function) EndDollarStringConstant

* For any other case of dollar-quoted string literals, just return one fat dollar-quoted string literal, now a new token type.

Also, I was going through the grammar and pom.xml. The pom.xml does not contain any specification to actually test the generated parser. It should.

**Comment by OleksiiKovalov** [comment]
Thanks for the advice and clarification!
I'll be glad to make grammar more standard&uniform

**Comment by gmai2006** [comment]
Thanks to @kaby76 for a much better explanation than my vague explanations.  If we follow the language specification the current grammar without action in the parser will work just fine.  The two examples that @OleksiiKovalov provided will be parsed correctly and the plsql are simple strings (DollarSignConstant) as illustrated in Figure 1.

@kaby76 about the lexer rule that determines the type of language, which is a literal value.  Can lexer actually do that without any action?  We already have issues with balancing the composite tokens and that is why we need a custom action.  Can we just leave grammar as it is - a function whose content is a string (as shown in Fig. 1)?  As I proposed in the previous messages, one can simply use Visitor and XPath to extract the function type and function body and pass it to the corresponding parser to handle it at a later stage thus there is no need to make the grammar more complicated

@OleksiiKovalov there are lots of minor issues with the current grammar that I discovered while performing the transformation and you are welcome to use my modified grammar as a baseline

Issues:
1. There are so many empty and unless nodes because of the epsilon rule so the tree is big and slow => replace the epsilon with optional
2. There are many unnecessary recursive rules (I think it is copied and pasted directly from the language spec) that cause the tree height very deep and make it very difficult to extract data => replace recursive rules with iterative. 
3. Add real nodes to certain branches to make it simple to parse and extract such as primary key vs foreign keys etc.  The real nodes are more preferable to labels.  Inheritance vs composition.  Make it easy to use XPath to search for certain information on the parse tree.

Figure 1.
![image](https://user-images.githubusercontent.com/722995/141604582-638ba40a-4206-4b6d-9867-4657d3b70a2f.png)

**Comment by OleksiiKovalov** [comment]
hi @gmai2006 , thanks for your considerations
originally grammar was adopted "as is" from original grammar with only small changes to make antlr happy
now I'm working on simplification, clarification, unification, and, mostly, performance improvements
Unfortunately, sometimes I face strange problems which I am unable to identify/solve by myself
Hoping that kaby76 will help/show the way to solve some problems

**Comment by kaby76** [comment]
> Can lexer actually do that without any action?

I think for now, leave the code as is, i.e., don't adjust for the dollar-quoted string literal as I suggested.

**Comment by OleksiiKovalov** [comment]
pl/sql code can be as dollar-quoted, as a single/double-quoted and like any other string type, used by PostgreSQL, so conversion is not as simple as I thought :(

**Comment by gmai2006** [comment]
@OleksiiKovalov Sorry I do not follow you.  Could you elaborate on the **conversion**?

**Comment by OleksiiKovalov** [comment]
hi @gmai2006 ,

pg/sql function is defined as 
CREATE FUNCTION somefunc(integer, text) RETURNS integer
AS **'function body text'**
LANGUAGE plpgsql;

where  'function body text' can be any of allowed strings  https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS
ege - simple string as 'return 0', c-style like 'return 0;\n', unicode string U&'d\0061t\+000061', dollar quoted (with nested dollar-quoted) like $FOO$ return $bar$oops!$bar$;$FOO$
- either with or without UESCAPE clause
so it is not enough to simply replace function definition with 

CREATE FUNCTION somefunc(integer, text) RETURNS integer
AS **BeginDollarStringConstant (stmtblock | pl_function) EndDollarStringConstant**
LANGUAGE plpgsql;

as suggested kaby76, we should also handle StringConstant, UnicodeEscapeStringConstant, and EscapeStringConstant which comes from lexer as a single token and it will require to add new lexer states etc which can hardly affect performance

so for now I've decided to add action to parse body definition and then incorporate it to the whole parsed tree.
It is convenient for the way I'm using this grammar

**Comment by OleksiiKovalov** [comment]
#2395

**Comment by gmai2006** [comment]
Again it is not really necessary to handle the PLSQL in the lexer.  One can simply do that using Visitor and XPath in the parse tree but if you insist I wish you the best.  I will close this ticket and you can use your ticket to continue with your changes.

**Comment by OleksiiKovalov** [comment]
> Again it is not really necessary to handle the PLSQL in the lexer. One can simply do that using Visitor and XPath in the parse tree but if you insist I wish you the best. I will close this ticket and you can use your ticket to continue with your changes.

as for now parsing of pl/sql during initial parse is implemented by a single call to a single method
I think it would be good to add an option like "AutoParsePLSql" with default to false
if anybody (like eg me) need to auto parse the whole script - they can set the option to true
I prefer such an approach with auto parse cause it is similar to other SQL dialects like t-sql in MS/Sybase, pl/sql in oracle 
also, I always parse the whole script in my app - so I'll anyway parse function definition - either during 1st or 2nd phase of parsing
