### ISSUE TITLE
philosophy of grammar 

### ISSUE THREAD

**Issue by OleksiiKovalov** [antlr/grammars-v4#2407]
Hi there, I have a simple question - "which features should grammar support/ how to write grammar"
Now I'm developing grammar "slightly wider" than official documentation, cause my main intention is to create a grammar that can parse syntactically correct source code. If it can parse "wider grammatic" - it is ok for me, I will not use it to check syntax.
from another point of view - official parse does not always describe how a specific parser works - eg T-SQL parser from MS can parse statements that do not follow official documentation (at least at my level of understanding)

So the question is: **is it good to create "wider" grammar "just in case"** - or it is needed to explore a specific parser to strictly follow how it works?

**Comment by KvanTTT** [comment]
Hi! The priority of usability in real scenarios is higher than following the official docs. So, we are welcome "wider grammatic".

**Comment by kaby76** [comment]
This is a good question, and opinions will vary. So, these rules are what I tend to follow.

* Each edition/version of the Spec should have its own grammar. That way we know what the hell is going on.
* Changes should be divided into getting the grammar to "work" (including optimizations) and extensions beyond the spec. Changes in the grammar to support extensions should be gated with a semantic predicate, so as they can be turned off if you want to follow the spec.
* You don't have to post the scraped grammar from the spec, but it would be appreciated. If you do, make sure it's placed in a separate directory, like "work/" or "ignore/", so we don't get confused as to what grammar one is supposed to use.

Some examples:

# Java:

The [Java Language Spec](https://docs.oracle.com/javase/specs/) is versioned, so it should have a separate grammar for each version and clearly named so we know what is being implemented. All the grammars in Section "Syntax" (e.g., [here](https://docs.oracle.com/javase/specs/jls/se17/html/jls-19.html)) contain mutual left recursion, ambiguous, and unoptimized (slow), so to what @KvanTTT said, they aren't that usable. Antlr cannot handle mutual left recursion so that has to be corrected. The grammar has numerous left and right recursions that can easily be converted to a rule with Kleene operators, which improves on performance (space and time) slightly. There are some really bad definitions, such as the typeName/packageOrTypeName/methodInvocation problem (see [this](https://github.com/antlr/antlr4/discussions/3346)), so these should be fixed.

# C++:

The C++ ISO/IEC 14882 Specification is versioned, so it should have a separate grammar for each. In fact, I should point out that the grammar here in this repo is from a *draft* not the official 2014 Spec, which I bought. This repo also does not contain the more recent versions of the language. If one is working from a draft Spec, make sure you say so. As most C++ sources are Windows or GNU specific, you have to make extensions to the grammar to parse these files. (GNU offers an option to "force" ISO compliance, but it still uses extensions!)
