### ISSUE TITLE
vb6 grammer MINUS issue

### ISSUE THREAD

**Issue by adrishdas** [antlr/grammars-v4#2508]
a=a -1 (no space before 1) throws an error whereas a=a - 1 (a space before 1) is handled correctly

**Comment by kaby76** [comment]
https://github.com/antlr/grammars-v4/blob/7bfee06e5bf167a92340d3e7f2228c63fa805803/vb6/VisualBasic6Lexer.g4#L431

You're not supposed to implement unary operators in the lexer grammar. It was in there since day one. https://github.com/antlr/grammars-v4/blob/4ecb19054ce6cfc07efb9050be5976aac7f6828f/vb6/VisualBasic6.g4#L868

**Comment by kaby76** [comment]
@adrishdas Please check out the updates and see if they solve your problem. --ken

**Comment by adrishdas** [comment]
The solution worked. Sorry, am quite late catch-up
