### ISSUE TITLE
Parser Exception: class PythonParser$NameContext cannot be cast to class  org.antlr.v4.runtime.tree.TerminalNodeImpl

### ISSUE THREAD

**Issue by Zero0one1** [antlr/grammars-v4#2537]
I downloaded the `PythonLexer.g4` and `PythonParser.g4` to parse Python files. Then put `PythonLexerBase.java`, `PythonParserBase.java`, and `PythonVersion.java` to my wroten Java file directory while commenting on their package line. I successfully compiled the java files but met a parser exception when executing.

> Parser Exception: 
java.lang.ClassCastException: class PythonParser$NameContext cannot be cast to class org.antlr.v4.runtime.tree.TerminalNodeImpl (PythonParser$NameContext and org.antlr.v4.runtime.tree.TerminalNodeImpl are in unnamed module of loader java.net.URLClassLoader @50acf55d)

```java
public void serializeFile(String f, String startSymbol){
...
      Lexer lexer = new PythonLexer(new ANTLRFileStream(f)); // f is a string to one python file
      CommonTokenStream tokens = new CommonTokenStream(lexer);
      vocab = lexer.getVocabulary();

      Parser parser = new PythonParser(tokens);
      parser.setErrorHandler(new BailErrorStrategy());

      Method method = parser.getClass().getMethod(startSymbol); // startSymbol is `root` according to Python grammar
      ParserRuleContext t = (ParserRuleContext) method.invoke(parser);
      parser.setBuildParseTree(false);
      setRuleNames(parser);

      t2 = System.currentTimeMillis();

      JSONArray tree = getSerializedTree(t, tokens); // Parser Exception line
      ...
}

private JSONArray getSerializedTree(RuleContext t, CommonTokenStream tokens) {
    ...
    String thisRuleName = getRuleName(t);
    String oldClassName = null;
    String oldMethodName = null;
    int oldBeginLine = 0;

    if (thisRuleName.equals("classdef")) {
      oldClassName = thisClassName;
    }
    if (thisRuleName.equals("funcdef")) {
      oldMethodName = thisMethodName;
      thisMethodName = ((TerminalNodeImpl) t.getChild(1)).getText(); // Parser Exception line
      oldBeginLine = beginLine;
      beginLine = ((TerminalNodeImpl) t.getChild(1)).getSymbol().getLine();
    }
    ...
}
```

**Comment by Zero0one1** [comment]
When I parse Java files using the above code (modifying the ANTLR grammar from Python to Java), it doesn't have the type conversion issues.

**Comment by Zero0one1** [comment]
I don't know if it's because I'm not familiar with ANTLR and programmed wrongly. Please tell me what should I post for your understanding. Thank you for your help!

**Comment by kaby76** [comment]
Well, it's crashing because you cannot convert a parser rule node into a terminal node. Only leaf nodes in the parse tree are can be a TerminalNodeImpl. Internal tree nodes are ParserRuleContext.

The rule you are operating with is:

```
funcdef
    : ASYNC? DEF name OPEN_PAREN typedargslist? CLOSE_PAREN (ARROW test)? COLON suite
    ;
```

Here, you have a FuncContext node with the first child as a TerminalNodeImpl for the "DEF", and the second child as a NameContext for the "name" in the rule. A NameContext is not derived from TerminalNodeImpl. 

GetText() is available for both TerminalNodeImpl and the NameContext. You don't need to typecast it to NameContext and then call GetText().

Using hardwired constants like "1" makes for fragile code. The input could have an "ASYNC". You should test to see that the "RuleContext t" can be casted to FuncdefContext, then use "func_def.name().GetText()", where "name()" is a function generated by Antlr to make sure to get the correct child for the parser rule "name".

To typecast to FuncdefContext, wrap the cast in a "try/catch" block.

NB: The grammars-v4/python/python grammar is currently not being tested. The python grammars were reorganized into the directory grammars-v4/python, the top-level pom.xml adjusted, and the grammars-v4/python/pom.xml added https://github.com/antlr/grammars-v4/commit/bd7e16faaca0a1de5db7b8b298ef475621c7ec67. Who knows when the python/python/ grammar was last tested, but it hasn't been updated for years so I would not use it. The only grammar I would (sort of) trust is grammars-v4/python/python3.

**Comment by Zero0one1** [comment]
I see. I switched to grammars-v4/python/python3 now but I got a new question. This ANTLR Python Parser grammar doesn't have a start symbol like `root` I used before.

So I want to decide which context is the root of the parse tree first: Single_inputContext, File_inputContext, or Eval_inputContext. Then call `parser.single_input()`, `parser.file_input()`, or `parser.eval_input()` correspondingly to start parsing the tree. But I couldn't find the suitable API from the API document or `Python3Parser.java` code.

May I ask what should I do to start the parsing?

**Comment by kaby76** [comment]
> I see. I switched to grammars-v4/python/python3 now but I [have] a new question. This ANTLR Python Parser grammar doesn't have a start symbol like `root` I used before.

Your input is from a file--you call `new ANTLRFileStream(f)`. Call the parser thus: `parser.file_input();`. The entry point for the parser for testing the grammar is in the pom.xml file.

In your code, `parser.setBuildParseTree(false);` is called after the parse, so it didn't have any effect. But, you want a parse tree anyway for `getSerializedTree()` since you pass "t" to it. You should remove `parser.setBuildParseTree(false);`.

Please migrate this question to StackOverflow.com. Thanks.

**Comment by Zero0one1** [comment]
Thank you for your help! I'll go to StackOverflow for further questions.
