### ISSUE TITLE
[C Language] Error Parsing of Structure Declarations

### ISSUE THREAD

**Issue by xurongchen** [antlr/grammars-v4#2607]
I have made a pull request to fix the problem.
[Pull Request 2608](https://github.com/antlr/grammars-v4/pull/2608)

## Problem Example:
```c
struct A { int x;};
```

In `c.g4`, `int x;` above is a `structDeclaration`, which has the following definition:

```antlr4
structDeclaration
    :   specifierQualifierList structDeclaratorList? ';'
    |   staticAssertDeclaration
    ;
```
A correct analysis should treat the identifier `x` as a part of `structDeclaratorList`.
However, with the definition for `structDeclaratorList` above. I found that
`x` was incorrectly parsed into `specifierQualifierList`. It is because `specifierQualifierList` may
contain `typedefName`, which finally can accept an identifier.

**Comment by CarlChenXueYi** [comment]
I don't think this paragraph is wrong because it can recognize that `x` is a `structDeclaratorList`
```
structDeclaration
    :   specifierQualifierList structDeclaratorList? ';'
    |   staticAssertDeclaration
    ;
```
![1](https://github.com/antlr/grammars-v4/assets/51503866/abae362f-f089-45ec-960b-4675e109f217)
This is the test I conducted, and I think adding that sentence is unnecessary (  `|   specifierQualifierList ';'`)
