### ISSUE TITLE
Java LSHIFT, RSHIFT and URSHIFT operators

### ISSUE THREAD

**Issue by DagSonntag** [antlr/grammars-v4#2756]
Hi
I don't follow why the java/java grammer (https://github.com/antlr/grammars-v4/blob/master/java/java/JavaParser.g4)  was written with a special syntax for the LSHIFT (<<), RSHIFT (>>) and URSHIFT (>>>) operators? As it is now it is very hard to identify if the expression is an "operator" expression of the LSHIFT, RSHIFT and URSHIFT type.

Line 571 and forward:
```
expression
    : primary
    | expression bop='.'
      (
         identifier
       | methodCall
       | THIS
       | NEW nonWildcardTypeArguments? innerCreator
       | SUPER superSuffix
       | explicitGenericInvocation
      )
    | expression '[' expression ']'
    | methodCall
    | NEW creator
    | '(' annotation* typeType ('&' typeType)* ')' expression
    | expression postfix=('++' | '--')
    | prefix=('+'|'-'|'++'|'--') expression
    | prefix=('~'|'!') expression
    | expression bop=('*'|'/'|'%') expression
    | expression bop=('+'|'-') expression
    | expression ('<' '<' | '>' '>' '>' | '>' '>') expression
    | expression bop=('<=' | '>=' | '>' | '<') expression
    | expression bop=INSTANCEOF (typeType | pattern)
    | expression bop=('==' | '!=') expression
    | expression bop='&' expression
    | expression bop='^' expression
    | expression bop='|' expression
    | expression bop='&&' expression
    | expression bop='||' expression
    | <assoc=right> expression bop='?' expression ':' expression
    | <assoc=right> expression
      bop=('=' | '+=' | '-=' | '*=' | '/=' | '&=' | '|=' | '^=' | '>>=' | '>>>=' | '<<=' | '%=')
      expression
    | lambdaExpression // Java8
    | switchExpression // Java17

    // Java 8 methodReference
    | expression '::' typeArguments? identifier
    | typeType '::' (typeArguments? identifier | NEW)
    | classType '::' typeArguments? NEW
    ;
```
 
Is there a special reason for this? If not I would suggest to change them to the bop syntax 
`| expression bop=('<<' | '>>>' | '>>') expression`
and update the lexer.g4 with the following lines (around row 188):
```
LSHIFT:             '<<';
RSHIFT:             '>>';
URSHIFT:            '>>>';
```.

**Comment by KvanTTT** [comment]
The following code:

```java
A<B<C>>> a;
```

won't be parsed correctly because `>>>` will be treated as `URSHIFT` instead of three `>` operators.

**Comment by kaby76** [comment]
The ['>' '>' hack](https://github.com/antlr/grammars-v4/blob/1e98d43a5c5439e14569df9bcc3eb5b86723ce8d/java/java/JavaParser.g4#L591) is done because of a delicate balance between parser and lexer. Antlr lexers generally operate independently from the parser context. Consider [SS.Sup&lt;provides&lt;Long&gt;.with&lt;Long&gt;&gt; s ](https://github.com/antlr/grammars-v4/blob/1e98d43a5c5439e14569df9bcc3eb5b86723ce8d/java/java/examples/AllInOne17.java#L558), where a templated variable is declared. Since the lexer is not aware of the parser context, we cannot have a blind rule like `GTGT: '>>';` because the lexer always matches the maximum string. We could add forward and/or backward scanning character semantic predicates in the lexer rule, but it would be difficult and messy. We could add parser context to the lexer, but you would also have to make sure the token stream is not buffered.

**Comment by KvanTTT** [comment]
On the other hand, with the plain lexer hack the following code is valid:

```
a >   > 1;
```

But it should not (whitespaces are not permitted inside shift operators). One of possible solution to check it is to use semantics predicate on parser.

**Comment by kaby76** [comment]
@KvanTTT That's true, but how would we allow "SS.Sup&lt;provides&lt;Long&gt;.with&lt;Long&gt;       &gt; s", but disallow "int x = 1 &gt;    &gt;  2;"? We need parser context, but we'd have to use unbuffered token streams--which we don't test with because we don't have a notion of using that in the pom.xml, and nothing in an Antlr grammar itself to force the use of unbuffered token streams.

**Comment by KvanTTT** [comment]
Yes, it's only possible to implement on the parser side. I mean something like this:

```
expression '>' '>' {checkNoSpaces()}? expression
```

**Comment by kaby76** [comment]
True, that would work, and better than the current situation. It should be fixed across several grammars in the repo besides java/java. The only "problem"--sort of--is that it's still two tokens from the lexer, and doesn't really mirror exactly the Java Spec.

**Comment by DagSonntag** [comment]
I see, thank you for the insights!
