### ISSUE TITLE
functioncall in lua/Lua.g4

### ISSUE THREAD

**Issue by renzet** [antlr/grammars-v4#279]
I didn't try if the grammar works because I don't know anything about a maven plugin (shame on me), but after reading the Lua grammar I am puzzled about how the functioncall in expressions (line nr 95-109) is reached:

It used to be part of the prefixexp term (and that is how the grammar is specified in the reference manual):

```
prefixexp
    : var | functioncall | '(' exp ')'
    ;
```

 but that part is commented out and replaced by a new term that doesn't include the functioncall:

```
prefixexp
    : varOrExp nameAndArgs*
    ;
```
I would expect since the functioncall term isn't part of the prefixexp anymore it would be included to the exp term on lines 95-109 but I don't see it there.

Can you elaborate on why you choose to comment the original terms out and replace them with the current ones?

Thanks,
Renze

**Comment by edwardros** [comment]
You don't need Maven to run a grammar; all you should need is the ANTLR4 jar and a JDK. The grammar can certainly parse much Lua code but I haven't confirmed whether the parse trees are correct.

It looks like prefixexp has been left factored; I assume this is because ANLTR4 doesn't support indirect left recursion which is present in the reference grammar.
In the official Lua grammar
{code}
prefixexp : var | functioncall | '(' exp ')';
functioncall : prefixexp args | prefixexp ':' Name args;
{code}
Is equivalent to the left factored
{code}
prefixexp : var | '(' exp ')' (args | ':' Name args)*
functioncall : var | '(' exp ')' (args | ':' Name args)+
{code}
Which is effectively what has been implemented.

**Comment by renzet** [comment]
Thanks for your answer, you are correct about the left recursion. I ran ANTLR in Eclipse and got the left recursion error when I changed prefixexp and functioncall in this grammar to match the reference grammar. 

I implemented a subset of the Lua language and added some actions to this grammar to construct my AST from source and so far I didn't find an error in the parse trees.

Regarding my question about why functioncall isn't included in the exp term:

```
I would expect since the functioncall term isn't part of the prefixexp anymore 
it would be included to the exp term on lines 95-109 but I don't see it there.
```
This is because the functioncall in exp is now directly included in prefixexp. In your answer that's more obvious than in this grammar because this grammar uses term names for varOrExp and nameAndArgs so thanks for that insight.
