### ISSUE TITLE
Question about completeness of Python grammar

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [antlr/grammars-v4#2792]
Heya, i just wanna know, is it feasible currently to attempt to make a Python interpreter using the antlr4 grammar? It'd be an interesting goal for me to work towards but want to know how complete it is currently

**Comment by kaby76** [comment]
The grammars that I am most familiar with are [python/python](https://github.com/antlr/grammars-v4/tree/master/python/python), which is a merged Python2/3 syntax grammar, and [python/python3](https://github.com/antlr/grammars-v4/tree/master/python/python3). AFAIK, either of these should be fine as for an interpreter.

The grammar isn't completely up to date, but there is a recent PR to update to something more recent. https://github.com/antlr/grammars-v4/pull/2782

NB: you will need to be careful with buffering associated with character and token streams since it sounds like you will be implementing a read-eval-print-loop interpreter. You may need to make your own implementations, but the Antlr runtime has several examples you can follow.

**Comment by RobEin** [comment]
[This](https://github.com/RobEin/ANTLR4-parser-for-Python-3.8.12) is the same as PR #2782 mentioned above.
It's not the latest version parser, but it faithfully reflects the official Python 3.8.13 grammar.

**Comment by Mythical-Forest-Collective** [comment]
Thank you for this information!
