### ISSUE TITLE
The priority is wrong

### ISSUE THREAD

**Issue by wutingjia** [antlr/grammars-v4#3149]
```g4
expression
    ：typeRef                                       #TypeRefExpr
    | expression bop=(LT|LE|GT|GE) expression       #CompareExpr
    | expression bop=(LT|LE|GT|GE)                  #CompareErrorExpr


typeRef
    : IDENTIFIER (LT typeRef (COMMA typeRef)* GT)?
    ;
```

I have 2 exprs as above. But the text `List<Integer>` can not match `TypeRefExpr` .It can only match the combination of `CompareErrorExpr` and `CompareExpr`. The priority of `TypeRefExpr` is higher than others, why it can cause this result?

**Comment by bkiers** [comment]
It parses just fine. Given the grammar:

```
grammar T;

parse
 : expression EOF
 ;

expression
 : typeRef                                       #TypeRefExpr
 | expression bop=(LT|LE|GT|GE) expression       #CompareExpr
 | expression bop=(LT|LE|GT|GE)                  #CompareErrorExpr
 ;

typeRef
 : IDENTIFIER (LT typeRef (COMMA typeRef)* GT)?
 ;


LT : '<';
LE : '<=';
GT : '>';
GE : '>=';
COMMA : ',';
IDENTIFIER : [a-zA-Z]+;
```

the following Java code:

```java
String source = "List<Integer>";
TLexer lexer = new TLexer(CharStreams.fromString(source));
CommonTokenStream stream = new CommonTokenStream(lexer);
stream.fill();

for (Token t : stream.getTokens()) {
    System.out.printf("%-20s'%s'%n",
        TLexer.VOCABULARY.getSymbolicName(t.getType()),
        t.getText().replace("\n", "\\n"));
}

lexer = new TLexer(CharStreams.fromString(source));
TParser parser = new TParser(new CommonTokenStream(lexer));
ParseTree root = parser.parse();
System.out.println("\n" + root.toStringTree(parser));
```

prints:

```
IDENTIFIER          'List'
LT                  '<'
IDENTIFIER          'Integer'
GT                  '>'
EOF                 '<EOF>'

(parse (expression (typeRef List < (typeRef Integer) >)) <EOF>)
```

Tested with ANTLR 4.11.1 and 4.12.0.

I am guessing you have minimized your grammar too much so that the problem you mention does not occur anymore. Also, you seem to be having an issue with a grammar you wrote yourself, while this repository is a collection of grammars of existing languages. A better place for you to ask a question regarding the use of ANTLR would be a place like [stackoverflow](https://stackoverflow.com). When deciding to ask there, be sure to include enough of the grammar so that the problem is reproducible. Best of luck!
