### ISSUE TITLE
Java keywords and Java field names conflict

### ISSUE THREAD

**Issue by Sidnio** [antlr/grammars-v4#3246]
java.lang.NullPointerException: Attempt to invoke interface method 'org.antlr.v4.runtime.Token org.antlr.v4.runtime.tree.TerminalNode.getSymbol()' on a null object reference

   java/lang/Class.java   930 Line

It is that when the class file is scanned, there is a conflict, and I don't know how to solve this problem.

![image](https://user-images.githubusercontent.com/33193340/225235414-02d98d81-b093-425c-91f6-e3bd581202e2.png)

![image](https://user-images.githubusercontent.com/33193340/225236130-d85e018f-1062-44b7-8ea0-9e3f6c764138.png)

![image](https://user-images.githubusercontent.com/33193340/225236151-ae816ed1-9aae-43aa-b9e5-929f695ffc32.png)

github https://github.com/Sidnio/AntlrTest

**Comment by kaby76** [comment]
I assume that is regarding the [java/java grammar](https://github.com/antlr/grammars-v4/tree/master/java/java). Instead of pictures, could you give the input file you are trying to parse, so I don't have to retype something that is a small view of a larger input file? Thank you.

**Comment by mlorek** [comment]
```java
class C{
private transient Module module;
private transient Module mOdule;
}
```

**Comment by mlorek** [comment]
not sure what exactly the problem here is, but I ran simple code and it worked for me.
variableDeclId can have an identifier or some tokens.
![image](https://user-images.githubusercontent.com/7452353/225288778-3bad92a5-0097-432b-a26e-cd3fe3d7a3ce.png)
but it is still possible to get the name of the ID:
   ```java
 @Override
    public void enterVariableDeclaratorId(JavaParser.VariableDeclaratorIdContext ctx) {
        String s = ctx.identifier().getChild(0).toString();
        System.out.println(s);
    }
```

**Comment by kaby76** [comment]
I don't know what the problem is. The gold standard is provide a driver. That's because the Intellij plugin uses "interpretation mode." It does not execute actions in a grammar.

Presumably, the complaint is then about the tokenization? Yes, according to the Spec:

> A further ten character sequences are restricted keywords: open, module, requires, transitive, exports, opens, to, uses, provides, and with. These character sequences are tokenized as keywords solely where they appear as terminals in the ModuleDeclaration, ModuleDirective, and RequiresModifier productions ([§7.7](https://docs.oracle.com/javase/specs/jls/se11/html/jls-7.html#jls-7.7)). They are tokenized as identifiers everywhere else, for compatibility with programs written before the introduction of restricted keywords. There is one exception: immediately to the right of the character sequence requires in the ModuleDirective production, the character sequence transitive is tokenized as a keyword unless it is followed by a separator, in which case it is tokenized as an identifier.

But, Antlr cannot easily do parser-dependent tokenization. The Antlr runtime method LT() does not take a parser state. Passing a pointer to the parser is insufficient because the state is actually an ATNConfigSet, used by AdaptivePredict(). The only way to change this would be a glorious hack via lexer modes.

**Comment by Sidnio** [comment]
https://github.com/Sidnio/AntlrTest

**Comment by Sidnio** [comment]
> 我假设这是关于[java / java语法](https://github.com/antlr/grammars-v4/tree/master/java/java)的。您能否提供您尝试解析的输入文件而不是图片，这样我就不必重新键入较大输入文件的不完整视图？谢谢。

https://github.com/Sidnio/AntlrTest

**Comment by Sidnio** [comment]
> https://github.com/Sidnio/AntlrTest

**Comment by Sidnio** [comment]
> 不确定这里的问题到底是什么，但我运行了简单的代码，它对我有用。变量DeclId 可以有一个标识符或一些令牌。 ![图像](https://user-images.githubusercontent.com/7452353/225289291-03fb764c-2b0a-499a-bd11-fd4853b6325f.png)
> 
> 但仍然可以获取 ID 的名称：
> 
> ```java
> @Override
>  public void enterVariableDeclaratorId(JavaParser.VariableDeclaratorIdContext ctx) {
>      String s = ctx.identifier().getChild(0).toString();
>      System.out.println(s);
>  }
> ```

https://github.com/Sidnio/AntlrTest

**Comment by KvanTTT** [comment]
@Sidnio please use only English. If you use any other language, unlikely somebody will help you.
