### ISSUE TITLE
Typescript grammar is broken. Base files are outdated and depend on abandoned `antlr4ts` package.

### ISSUE THREAD

**Issue by iSuslov** [antlr/grammars-v4#3314]
After you compile the grammar files for typescript, you need [base files](https://github.com/antlr/grammars-v4/tree/master/javascript/typescript/TypeScript) that depend on abandoned `antlr4ts` package. It seems that types have changed so much, you get errors all over the place when you change imports in this files to `antlr4` and install `@types/antlr4` package. 

Obviously even if you ignore those errors and compile, code doesn't work. 

 
<img width="1157" alt="Screenshot 2023-04-02 at 11 06 57 PM" src="https://user-images.githubusercontent.com/7628774/229402386-cf4bd450-beae-4a0f-9296-2fd3be4fc2bd.png">

**Comment by iSuslov** [comment]
Also after spending some time looking closer into the errors, I don't understand how this grammar can work in a first place.

It sometimes has references to the method `notLineTerminator()` without `this`:

https://github.com/antlr/grammars-v4/blob/22ba8de514996291c6e951f698988d83b7d968aa/javascript/typescript/TypeScriptParser.g4#L163-L167

Which produces code with errors:

<img width="592" alt="Screenshot 2023-04-02 at 11 30 35 PM" src="https://user-images.githubusercontent.com/7628774/229405097-f0a8ffa3-d975-4d40-a55c-46888aad19ce.png">

**Comment by kaby76** [comment]
The only targets that "work" are CSharp and Java. https://github.com/antlr/grammars-v4/blob/22ba8de514996291c6e951f698988d83b7d968aa/javascript/typescript/desc.xml. That is the definitive guide to let us know what targets work, not the code that is there. The tests that exist are in examples/. They appear to parse because there are no .errors files paired with the inputs. If the target builds and parses all input, the target is declared to "work". Expected errors from a parse will be in the .errors files. The official Typescript taget only came out a month ago, and no one has fixed the code yet. At the time, I generated the desc.xml automatically, testing every target against the grammar. I was more concerned on getting a functional, incremental build working rather than try to fix all 300 grammars, in which tests would take all day to run. For this grammar, the work is unfinished: a dozen test files hardly qualifies a parser. There should be hundreds.

**Comment by sigmaith** [comment]
Hi, I want to get an ast about type definition using the typecheck grammar in ts. I think the listener implementation is essential for this, is there a tutorial on this? Or I want to get some help on how to run the experiment example. Or is this all impossible?

**Comment by kaby76** [comment]
> Hi, I want to get an ast about type definition using the typecheck grammar in ts. I think the listener implementation is essential for this, is there a tutorial on this? Or I want to get some help on how to run the experiment example. Or is this all impossible?

The TypeScript/ port is still broken. Fortunately, it can be easily fixed (I got it working). My plan is to write a PR today to change the existing code in [TypeScript/](https://github.com/antlr/grammars-v4/tree/5e7540fae7588cf1529fc398cb3d8ee691890ded/javascript/typescript/TypeScript) to use "Official Antlr4 TypeScript", not "Antlr4ts". I'm wary of moving this code to an "Antlr4ts/" directory because Trgen doesn't know what that port is. Trgen already has an "Antlr4ng" target, which is Mike Lischke's fork that fixes some issues with "Official Antlr4 TypeScript". You should be able to write a listener and/or visitor using the ["Official doc for TypeScript"](https://github.com/antlr/antlr4/blob/dev/doc/typescript-target.md).

That said, this grammar is old an hasn't been updated for some time.
