### ISSUE TITLE
Casting and :: lambda expressions not parsed correctly in Java/Java grammar

### ISSUE THREAD

**Issue by DagSonntag** [antlr/grammars-v4#3342]
Hi
I am sitting with the following java code and the Java/Java grammar
```
public class LambdaOrder {
    void forEachRemaining(Consumer<? super Double> action) {
            forEachRemaining((DoubleConsumer) action::accept);
    }
}
```

In the existing grammar this parses the Casting and Lambda incorrectly into the following parse-tree:
![image](https://user-images.githubusercontent.com/32261711/233963095-c4e94771-6db6-449b-8b4b-c6a7542f6553.png)

As can be seen there the casting is "applied" on the "action" identifier there, while it should be applied on the whole lambda as seen here:
![image](https://user-images.githubusercontent.com/32261711/233963317-bf25cf5a-2b83-4163-a56d-fa442e9c6696.png)

This can be solved by changing the order of the casting and :: rules in the expression grammar in the grammar-file.
 (existing syntax is:
```
 expression
    : primary
       ...
    | '(' annotation* typeType ('&' typeType)* ')' expression
      ...
    | expression '::' typeArguments? identifier
    ...
```
 
While the following syntax solves the issue: 
```
expression
    : primary
       ...
    | expression '::' typeArguments? identifier
    | '(' annotation* typeType ('&' typeType)* ')' expression
     ...
```
)

However, I don't understand why this solves the issue?  Does the parsing not start from the outside in, i.e. for`forEachRemaining((DoubleConsumer) action::accept);` it starts with finding the method (with expressions), then take a single expression which it first identifies as a casting expression (since it is before the :: rule), and then finds the sub-expression to the casting expression to be a :: case?

Or does the syntax start from inside out? First identifying `(DoubleConsumer) action` and then go on to `(DoubleConsumer) action::accept`?

Also, is the solution good, or is the correct way to use <assoc=right> rules here instead.

Thankful for any clarifications! I can make the correct pull request after discussions :)

**Comment by kaby76** [comment]
The `expression` rule must be carefully redone using a precedence table, e.g., https://introcs.cs.princeton.edu/java/11precedence/. Notice that in this table, casting is lower priority than binary operators `+` and `-`, but in the grammar, it's higher priority than these operators. If one goes through all the operators in the table and compares it to the precedence declared in the rule, there are a lot of errors.

I wonder whether this should be implemented entirely differently using the hierarchy of rules for expressions in the spec, but with a parser tree listener to fix the tree.

**Comment by DagSonntag** [comment]
Mmm, I have seen the table, and think we can implement it that way. However, I have never seen where the colon-colon syntax (Java 8 methodReference) is located in that table. It cannot be at level 0 since it must have higher precedence than casting as can be seen in this example. So I guess it would have level 15 or?

Is there a reason why one would like to implement it as a parse tree listener instead? Seems like making it more complicated than just following the right order here and going away from the simplicity the file has now?

**Comment by kaby76** [comment]
The `::`-operator isn't in the table because it's not considered an "operator" for "expressions". Instead, it's part of `Primary`/`PrimaryNoNewArray`/`MethodReference` (see the [Spec](https://docs.oracle.com/javase/specs/jls/se20/html/jls-15.html#jls-15.13)). The alts were introduced two years ago from the JLS 11 by successive unfolding of these rules into `expression`, but it's not clear why it had to be unfolded. In any case, [these alts](https://github.com/antlr/grammars-v4/blob/2c2fd331cdb6fd1016da92e39352542e47fd60d0/java/java/JavaParser.g4#L609-L611) should be yanked further up in the expression rule.

I have thought about, but haven't yet designed, an algorithm for refactoring a cascaded-expression rule implementation into an Antlr-style rule implementation for operator precedence and associativity. [Trash](https://github.com/kaby76/Domemtech.Trash) would be used for the implementation, but it is still missing some essential pieces.

A tree listener could rewrite the tree so that the trees are more compact for a cascaded-rule implementation. The whole point of refactoring expression rules is to give smaller trees and faster parses. But, a faster parse is not a guarantee. A tree rewrite could allow one to work with the casade style, avoid all these alt-order issues, but still have smaller parse trees.

**Comment by DagSonntag** [comment]
I see.
Well, I made a merge request where updated the order now to fit the table (to the best of my abilities). For me it is still unclear if the method-reference is in the exact right place, but it works with all the examples I can come up with. I am also unclear exactly where the switch expressions fit in, but have found no parsing issues with having it in the current place. Maybe you can share some insights?

It might be an idea to use some more advanced setup, but hopefully we can at least close this issue with this merge request?
