### ISSUE TITLE
`ANTLR Tool version 4.13.0 used for code generation does not match the current runtime version 4.11.1` on `mvn clean install`

### ISSUE THREAD

**Issue by ris58h** [antlr/grammars-v4#3588]
1. Go to `css3` grammar.
2. `mvn clean install`

```
[INFO] --- antlr4test:1.22:test (default) @ CSS3 ---
[INFO] Evaluating Scenario: Default Scenario
[INFO] Parsing :/Users/ris/projects/grammars-v4/css3/examples/mdn-at-font-face.css
ANTLR Tool version 4.13.0 used for code generation does not match the current runtime version 4.11.1
ANTLR Runtime version 4.13.0 used for parser compilation does not match the current runtime version 4.11.1
ANTLR Tool version 4.13.0 used for code generation does not match the current runtime version 4.11.1
ANTLR Runtime version 4.13.0 used for parser compilation does not match the current runtime version 4.11.1
[INFO] Parsing :/Users/ris/projects/grammars-v4/css3/examples/bootstrap.min.css
```

**Comment by kaby76** [comment]
The root pom.xml contains [one version for Antlr4 (4.13.0)](https://github.com/antlr/grammars-v4/blob/c9e5c8caca0b562805711b22d04a8ce39d012461/pom.xml#L14), but the plugin [sets a different version](https://github.com/antlr/antlr4test-maven-plugin/blob/fbba99e1ecebe03681e1269a0a1fba95f75550c3/pom.xml#L41). The version selected in grammars-v4 is not overriding the version in the plugin as intended. The easiest would be to update the plugin, upgrade here. But that would not fix an entry in the root pom.xml that does not work. Why even have it? [The latest version of the plugin is 1.22](https://search.maven.org/artifact/com.khubla.antlr/antlr4test-maven-plugin/1.22/maven-plugin).

**Comment by kaby76** [comment]
I added an issue requesting a new version of the plugin be published. https://github.com/antlr/antlr4test-maven-plugin/issues/89

The problem is that the version in the grammars-v4/pom.xml is the version of the tool, but the version of the Antlr Java runtime is 4.11.1. The tester should not be using two different version numbers. This, again, is why you should be using the Trash toolkit. It uses one, and only one, version number for the tool and runtime, not only for Java, but for all targets.

The alternative is to keep the version fixed on both tool and runtime and never ever change it. This would mean any grammars that have been updated to use specific features of a new version of Antlr have to be removed from Maven testing, or we request a new version of the plugin. I am anticipating the next version of Antlr to have StringTemplate actions, to clean out the "transformGrammars.py" hack.

**Comment by kaby76** [comment]
@ris58h Please update and check that the fix works.

**Comment by ris58h** [comment]
@kaby76 no warnings anymore. Thanks!
