### ISSUE TITLE
[PL/SQL] warning(154): PlSqlParser.g4:6241:0: rule json_function contains an optional block with at least one alternative that can match an empty string

### ISSUE THREAD

**Issue by doberkofler** [antlr/grammars-v4#3646]
When compiling grammar/PlSqlParser.g4 I get a warning:

$ antlr4 -Dlanguage=Python3 grammar/PlSqlParser.g4
```bash
warning(154): PlSqlParser.g4:6241:0: rule json_function contains an optional block with at least one alternative that can match an empty string
```

**Comment by kaby76** [comment]
It's caused by the expression [json_query_returning_clause?](https://github.com/antlr/grammars-v4/blob/eba5c4487067292a82cf6b753f33a6b546c7e1df/sql/plsql/PlSqlParser.g4#L6246C64-L6246C92)--the `?` operator cannot be applied to a symbol that is nullable. Unfortunately, it's in the Spec. https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/JSON_QUERY.html#GUID-6D396EC4-D2AA-43D2-8F5D-08D646A4A2D9.

The easiest fix is to change the rule to not use the `?`-operator.

```
$ diff PlSqlParser.g4 ..
6246c6246
<     | JSON_QUERY '(' expression (FORMAT JSON)? ',' CHAR_STRING json_query_returning_clause json_query_wrapper_clause? json_query_on_error_clause? json_query_on_empty_clause? ')'
---
>     | JSON_QUERY '(' expression (FORMAT JSON)? ',' CHAR_STRING json_query_returning_clause? json_query_wrapper_clause? json_query_on_error_clause? json_query_on_empty_clause? ')'
```

The other is to rewrite json_query_on_empty_clause to not derive the empty string.

**Comment by kaby76** [comment]
Can this be closed? I fixed this several weeks ago. T.Y.
