### ISSUE TITLE
tsql.g4 security_statement multiple principal

### ISSUE THREAD

**Issue by alfoos** [antlr/grammars-v4#422]
tsql.g4 don't allow multiple principal for security_statement rule.

eg statement:

`GRANT EXECUTE ON [dbo].[closeLead] to Public,XYZPublic`

This generates following warning: 

`no viable alternative at input 'GOGRANTEXECUTEON[dbo].[closeLead]toPublic'
no viable alternative at input 'Public'`

ref:
https://github.com/antlr/grammars-v4/blob/master/tsql/tsql.g4#L522
https://msdn.microsoft.com/en-us/library/ms187965.aspx

**Comment by ohyesboy** [comment]
There are 2 problems here,
1. The 'to principal' should appear 0-N times according to https://msdn.microsoft.com/en-us/library/ms187965.aspx, but in our file it's not.
2. Public keyword is not accepted as id here, since I do not find how microsoft defined principal, it will be easier to treat it as an other simple_id this context.

I may issue a PR to fix this. After fix, the parse tree should look like:

![image](https://cloud.githubusercontent.com/assets/3621688/22665524/07767d7a-ec83-11e6-9c5c-2ac1d4904901.png)

**Comment by ohyesboy** [comment]
PR here https://github.com/antlr/grammars-v4/pull/554
