### ISSUE TITLE
Strange Python parser for Lua 5.4

### ISSUE THREAD

**Issue by boolangery** [antlr/grammars-v4#4286]
Hey,

I generated the Python3 parser code with the Lua grammar in https://github.com/antlr/grammars-v4/tree/master/lua

In the generated code, reference to [LuaLexerBase.py](https://github.com/antlr/grammars-v4/blob/master/lua/Python3/LuaLexerBase.py) are generated like this:

```python
    def COMMENT_action(self, localctx:RuleContext , actionIndex:int):
        if actionIndex == 0:
             this.HandleComment(); 
```

It obviously crashes on `this`.

Any help appreciated

**Comment by kaby76** [comment]
Actions (`{ ... }` or `{ ... }?`) in Antlr4 grammar files is target specific. In order to have the grammar file work for all targets, it has to be in "target agnostic format".

"Target agnostic format" means that the Antlr actions are target-specific (Python3 or C# or Java ...) but in a minimal syntax to be compiled for the target. It is syntactically and semantically a method call. Unfortunately "target agnostic format" does not work perfectly because there is still minor variations. For example, to call a method on a class in C++, `this.` has to be instead `this->`.

To get around this last syntactic issue for a target, you need to apply [transformGrammar.py](https://github.com/antlr/grammars-v4/blob/2b4757494d23851b8d71aedc18a048a3e5dd6c46/lua/Python3/LuaLexerBase.py) to the grammar files. `python3 transformGrammars.py`

Make sure to read the [Wiki](https://github.com/antlr/grammars-v4/wiki).

**Comment by boolangery** [comment]
Thank you for your quick answer, then problem solved!
