### ISSUE TITLE
PlSqlLexer.g4 produces references to "this" in generated Python code

### ISSUE THREAD

**Issue by piotrlg9** [antlr/grammars-v4#4338]
Part of grammar "PlSqlLexer.g4" has references to "this" instead of "self" and this code is produced in output Python code, see:

```
REMARK_COMMENT:
    'REM' {this.IsNewlineAtPos(-4)}? 'ARK'? (' ' ~('\r' | '\n')*)? NEWLINE_EOF -> channel(HIDDEN)
;

// https://docs.oracle.com/cd/E11882_01/server.112/e16604/ch_twelve032.htm#SQPUG052
PROMPT_MESSAGE: 'PRO' {this.IsNewlineAtPos(-4)}? 'MPT'? (' ' ~('\r' | '\n')*)? NEWLINE_EOF;
```

This code must be corrected after each generation ("this." -> "self.").
Please correct the grammar for Python (somehow).

**Comment by kaby76** [comment]
Please read the doc. Step 4. https://github.com/antlr/grammars-v4/wiki#manually

You have to run `python  transformGrammar.py`.

The grammars in this repo are "target agnostic" so there is one copy of the grammar for all targets. Otherwise people fork the grammars, create version skews because they only work in one target and mess it up for other targets.

**Comment by piotrlg9** [comment]
Looks like this is the piece I was looking for, thanks!
