### ISSUE TITLE
VB6 grammar failing on Dollar signs in value statements

### ISSUE THREAD

**Issue by maxiz** [antlr/grammars-v4#516]
The VB6 grammar seems to be unable to parse statements like
`filepath$ = filename.Text$ & "\abc" & filepath$ & ".txt"` 
`If Func1(filname.Text$ & "\Logfiles", True) = True Then`

Removing the $ from filename.Text$ would solve the issue. 

Any help in identifying the parser rule causing the problem is much appreciated!

**Comment by Hinaser** [comment]
Hi.
I'm using vb6 grammar in my work and I believe I can tell you something.

First of all, I don't know whether '$' is allowed to be used in variable name in vb6.
I found the [article](https://msdn.microsoft.com/en-us/library/office/gg264773.aspx) in MSDN that '$' is not allowed for variable names in 'VBA'. (I'm not sure this applies to VB6)

If it is, the root cause is in lexer rule, not in parser rule.
In the current vb6 grammar, identifier (variable name, function name, procedure name, etc) is composed of 'letters' and 'digits'. 

Definition of identifier in the vb6 grammar is:
```
IDENTIFIER
   : LETTER LETTERORDIGIT*
   ;
```

So if you have confidence that '$' should be able to use as variable name, modify the grammar above like below.
```
IDENTIFIER
   : LETTER (LETTERORDIGIT | DOLLAR)*
   ;
```

Please remember that '$' still cannot be placed at the first char for variable name.
If '$' can be used as the first char, you should modify the grammar like this:
```
IDENTIFIER
   : (LETTER | DOLLAR) (LETTERORDIGIT | DOLLAR)*
   ;
```

Hope this helps.

**Comment by Hinaser** [comment]
(I deleted my previous post because it was so inaccurate)

Hi
I tested in my local environment using vb6 grammar file in this repository.

I tried to parse the script below and found no errors.

```
filepath$ = filename.Text$ & "\abc" & filepath$ & ".txt"
If Func1(filname.Text$ & "\Logfiles", True) = True Then
  someVar = 1
end if
```
Parse tree was generated as below. I don't see any errors in lexing/parsing.
![Imgur](http://i.imgur.com/hCCAeqt.png)

**Comment by maxiz** [comment]
I tested the TypeHint rule again and it passed fine. So maybe I made a mistake during the first test. 
Closing the issue.
