### ISSUE TITLE
Generated Python3 lexer contains non-Python code

### ISSUE THREAD

**Issue by Lawouach** [antlr/grammars-v4#547]
Using antlr-4.6, running the following:

```
$ antlr4 -Dlanguage=Python3  Python3.g4
```

The generated PythonLexer.py module contains non-Python code that makes the module unusable.

Here is a snippet of what is generated:

```python
def __init__(self, input=None):
    super().__init__(input)
    self.checkVersion("4.6")
    self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
    self._actions = None
    self._predicates = None

  // A queue where extra tokens are pushed on (see the NEWLINE lexer rule).
  private java.util.LinkedList<Token> tokens = new java.util.LinkedList<>();

  // The stack that keeps track of the indentation level.
  private java.util.Stack<Integer> indents = new java.util.Stack<>();
```

**Comment by KvanTTT** [comment]
Actually, this is not error. Python3 grammar written for Java runtime, so you should rewrite code fragments (actions) on python.

**Comment by Lawouach** [comment]
Hey @KvanTTT,

Thanks for the feedback but I don't quite understand you meant. Do you imply I have to re-implement manually those Java code in Python?

**Comment by KvanTTT** [comment]
Yes, you have to replace Java code with Python.

**Comment by Lawouach** [comment]
Gotcha! Thanks :)

**Comment by aptrishu** [comment]
@Lawouach did you modify the code ? and is it working ?

**Comment by Lawouach** [comment]
I didn't because I didn't need that code in the end. sorry.

**Comment by aptrishu** [comment]
@KvanTTT Can I get the Python3 grammar for Python target somewhere? It's hard to modify the code because Python runtime's `Lexer.py` lacks some of the methods than its java counterpart.

**Comment by GraydenH** [comment]
Why is this closed? it seems like a shortcoming and should be fixed. Also, does anyone know of a complete implementation anywhere?

**Comment by teverett** [comment]
Issue is reopened. @GraydenH are you will to take a look at replacing the inline Python w/ Java?

**Comment by GraydenH** [comment]
@teverett I don't really know much about antlr, I can attempt to fix the inlined code though

**Comment by aptrishu** [comment]
There is a PR for it https://github.com/antlr/grammars-v4/pull/572 @GraydenH . Its failing some tests, I havent looked at it since then.. Take a look if you want.

**Comment by GraydenH** [comment]
Not sure where to put this, so putting it here.

[inline-fix.zip](https://github.com/antlr/grammars-v4/files/953389/inline-fix.zip)

the inline-java files are the original outputted java snippets and the fixed-python files are the corrected segments. They run and the interpreter does not complain. have not have the chance to thoroughly test it. I've included the full Python3Lexer.py. 

There were also parts after the second segment that had to be changed from some_var++ to some_var = some_var + 1, or equivalent. This is included in the full lexer file. I also used a deque instead of a linked list.


@teverett to clarify your statement about "replacing the inline Python w/ Java" the issue was that java is showing up in a python file, not the other way around.

This is a quick fix, for anyone stuck in this limbo like I was

**Comment by aptrishu** [comment]
It is getting merged so now you can use it. https://github.com/antlr/grammars-v4/pull/883

**Comment by aquaktus** [comment]
Hi,

I'm having this same issue now. What is the solution?
Is it to make our own python version of the java code?

**Comment by aptrishu** [comment]
I had already written one. You shouldn't get this error anymore. check the
repo.
