### ISSUE TITLE
Please add Typescript Grammar

### ISSUE THREAD

**Issue by jeep87c** [antlr/grammars-v4#858]
ECMAScript is already supported but TypeScript is currently missing.

It would be nice to add this grammar to this repo.

Regards

**Comment by fsomme2s** [comment]
Is anyone working on this?

**Comment by Deathnerd** [comment]
Has there been any progress on this? I could also use a TypeScript parser for JVM

**Comment by fsomme2s** [comment]
@Deathnerd Hi, sorry I totally forgot to open source my results... I followed my plan that I layed out above and got something more or less running but it's not recognizing many typescript strucutures.
I will find me some time in the next days to clean up my work and push it to github.

Turned out that the javascript parser I mentioned above is not exactly compatible with the actual ecma script standard. It uses many "shortcuts" to get rid of the many rules of the grammatic published in the ecmascript standard.

While this is great for the usability of the javascript parser, it makes it somewhat harder to build a typescript grammar on top of it.

**Comment by Deathnerd** [comment]
Awesome! Thanks for getting this out! I've forked it already and look to using it in my projects :D

**Comment by studentmain** [comment]
As #1518, can we close this issue now?

**Comment by KvanTTT** [comment]
I think yes :)
